swagger: "2.0"
info:
  version: 0.0.0
  title: Masters for Collection System  
  description: Specification of all the master data APIs required for Collection Management System.

host: phoenix-qa.egovernments.org
schemes:
  - https
basePath: '/v1/[API endpoint]'

paths: 
  /paymentModesNotAllowed/_create:     
    post:
      summary: Create Payment Modes Not allowed for the Department.
      description: Create Payment Modes Not allowed for the Department.
      parameters:
        - name: paymentModesNotAllowed
          in: body
          description: Payment Modes Not Allowed.
          required: true
          schema:
            $ref: '#/definitions/PaymentModesNotAllowedReq'
      responses:
        '201':
          description: Payment Modes Not allowed for the department mapped successfully.
          schema:
            $ref: '#/definitions/PaymentModesNotAllowedRes'
        '400':
          description: Invalid input.
      tags:
        - Payment Modes Not Allowed
    
        
definitions:
  PaymentModesNotAllowedReq:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique id of tenant.
        format: varchar
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      PaymentModesNotAllowed:
        $ref: '#/definitions/PaymentModesNotAllowed'
        
  PaymentModesNotAllowedRes:
    type: object
    properties:
      tenantId:
        type: string
        description: Unique id of tenant.
        format: varchar
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      PaymentModesNotAllowed:
        $ref: '#/definitions/PaymentModesNotAllowed'
        
  PaymentModesNotAllowed:
    type: object
    properties:
      department:
        type: object
        description: Reference from Common Services Department.
      modesNotAllowed:
        type: string
        description: Pipe seperated value needs to be persisted for modes not allowed ex. Cash|Cheque
