swagger: '2.0'
# eGSP YAML Template Version: 1.0 
# This is a version number for the YAML template. This must not be changed.

info:
  version: 1.0.0
  title: Performance Management APIs
  description: |
    APIs available for Performance Management
      - Create and Define KPIs
      - Search and View KPI defined
      - Set Target for KPIs for the Tenants / ULBs
      - Enter Actual Values for the KPIs 
      - Search KPI Values based on different parameters
      - Search and Compare KPI Values for different ULBs / Fin Years/ KPIs
  contact:
    name: Darshan Nagesh
host: phoenix-qa.egovernments.org
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json  
basePath: '/performance-assessment/'
paths:
  /kpi/master/_create:
    post:
      summary: Creates a KPI Master Record with KPI Detailing
      description: KPI which is applicable for all the ULBs are created with a description to it. This provides a detail on KPI and its base attributes
      tags:
        - KPI Master
      parameters:
        - name: KPI
          in: body
          description: required parameters have to be populated
          required: true
          schema:
            $ref: '#/definitions/KPIRequest'
      responses:
        '201':
          description: Acknowledgment on successful creation of new KPI
          schema:
            $ref: "#/definitions/KPIResponse"
        '400':
          description: Creating a new KPI Request has failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
        '404':
          description: tenantId provided was not found
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
            
  /kpi/master/_update:
      post:
        summary: API to update the values of the KPI Master
        description: Updates the existing values of the KPI Master (Code cannot be updated)
        tags:
          - KPI Master
        parameters:
          - name: KPI
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIRequest'
        responses:
          '200':
            description: KPI Master Record has been updated successfully 
            schema:
              $ref: "#/definitions/KPIResponse"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
  
  /kpi/master/_search:
    post:
      summary: Fetch the KPI Master Record
      description: Search the KPI Record based on the different parameters such as code, name
      tags:
        - KPI Master
      parameters:
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo"
        - $ref: "#/parameters/name"
        - $ref: "#/parameters/code"
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
        - $ref: "#/parameters/sortResult"
      responses:
        200: 
          description: Successful response
          schema:
            $ref: "#/definitions/KPIResponse"
        400:
          description: Invalid input
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
            
  
              
  /kpi/master/_delete:
      post:
        summary: API to delete the exisiting record of the KPI Master
        description: Soft Deletes the existing values of the KPI Master
        tags:
          - KPI Master
        parameters:
          - name: KPI
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIRequest'
        responses:
          '200':
            description: KPI Master Record has been deleted successfully 
            schema:
              $ref: "#/definitions/KPIResponse"
          '400':
            description: Request failed
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  # KPI and Target APIs
  /kpi/target/_create:
      post:
        summary: This API is used to define the Target Values for each KPI 
        tags:
          - KPI Targets
        parameters:
          - name: KPITarget
            in: body
            description: Required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPITargetRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPITargetResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpi/target/_update:
      post:
        summary: This API is used to update the already existing target Values for each KPI 
        tags:
          - KPI Targets
        parameters:
          - name: KPITarget
            in: body
            description: Required parameters have to be populated 
            required: true
            schema:
              $ref: '#/definitions/KPITargetRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPITargetResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpi/target/_search:
    post:
      summary: Fetch the target value defined for the KPI
      description: Search the KPI Target Values defined for the KPI Record 
      tags:
        - KPI Targets
      parameters:
        - $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/parameters/requestInfo"
        - $ref: "#/parameters/kpiId"
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
        - $ref: "#/parameters/sortResult"
      responses:
        200: 
          description: Successful response
          schema:
            $ref: "#/definitions/KPITargetResponse"
        400:
          description: Invalid input
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
    # KPI and Actual Value Setting APIs
  /kpi/value/_create: 
      post:
        summary: This API is used to enter the values (Actuals) for the KPI at ULB Level
        tags:
          - KPI Value
        parameters:
          - name: KPIValue
            in: body
            description: Required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIValueRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPIValueResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpi/value/_update: 
      post:
        summary: This API is used to update the already existing values (Actuals) for the KPI at ULB Level
        tags:
          - KPI Value
        parameters:
          - name: KPIValue
            in: body
            description: Required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIValueRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: '#/definitions/KPIValueResponse'
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
              
  /kpi/value/_search: 
      post:
        summary: Fetch the target value defined for the KPI
        description: Search the KPI Target Values defined for the KPI Record 
        tags:
          - KPI Value
        parameters:
          - name: kpiValueSearchRequest
            in: body
            description: required parameters have to be populated
            required: true
            schema:
              $ref: '#/definitions/KPIValueSearchRequest'
        responses:
          200: 
            description: Successful response
            schema:
              $ref: "#/definitions/KPIValueSearchResponse"
          400:
            description: Invalid input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
            

            


definitions:
  
  KpiTarget:
    type: object
    description: Target for the KPI Record for each Tenant ID
    properties:
      id: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: unique identifier of a KpiTarget object
      kpiCode:
        type: string
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Code given to the KPI
      targetValue: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Value for the KPI Target
      targetDescription: 
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Detailed description for target value in words
      instructions: 
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Instructions on how to achieve the target
      createdBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who created the record
      lastModifiedBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who last updated the record
      createdDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record got created
      lastModifiedDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record for modified
    required:
      - kpiCode
      - targetValue
      
  
  KpiValue:
    type: object
    description: Object which holds the mapping for KPI and its actual values entered by ULBs
    properties:
      id: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: unique identifier of a KPI Value object
      kpiCode:
        type: string
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Code given to the KPI
      actualValue: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Actual Value at ULB Level for the KPI Target
      tenantId:
        type: string
        readOnly: true
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Identifier of the tenant
      documents:
        type: array
        items:
          $ref: "#/definitions/Document"
      createdBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who created the record
      lastModifiedBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who last updated the record
      createdDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record got created
      lastModifiedDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record for modified
    required:
      - kpiCode
      - actualValue
      - tenantId
      
  KpiValueList:
    type: object
    description: Object which holds the list of KPI Values for each tenant or financial year
    properties:
      tenantId:
        type: string
        readOnly: true
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Identifier of the tenant
      kpiCode:
        type: string
        readOnly: true
        pattern: ^[a-zA-Z0-9]+$
        description: unique identifier of a KPI object
      finYear:
        type: string
        pattern: ^[a-zA-Z0-9-]+$
        description: Financial Year for which the KPI is applicable
      kpiTarget:
        $ref: '#/definitions/KpiTarget'
      kpiValue:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValue'

  Document:
    type: object
    description: documents required under respective KPI 
    properties:
      id:
       type: integer
       format: int64
       pattern: ^[0-9]+$
       description : Unique identifier of the Document.
      name: 
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: name of the Document.
        readOnly: true
      code: 
        type: string
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Code of the Document.
        readOnly: true
      kpiCode:
        type: string
        readOnly: true
        pattern: ^[a-zA-Z0-9]+$
        description: unique identifier of a KPI object
      description:
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: description of the Document.
        maxLength: 250
      active:
        type: boolean
        format: varchar
        description: TRUE for active Document Names and FALSE for inactive Document Names.
      auditDetails:
        $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/AuditDetails"
    required:
      - id
      - active
      - name
      - description
  

  KPI:
    type: object
    description: This is the object for KPI Details not specific to any ULB
    properties:
      id:
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: unique id of the KPI
      name:
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Name of the KPI
      code:
        type: string
        pattern: ^[a-zA-Z0-9]+$
        description: Unique Code given to the KPI
      description:
        type: string
        pattern: ^[a-zA-Z0-9 ]+$
        description: Description for the KPI 
      kpiTarget:
        $ref: '#/definitions/KpiTarget'
      finYear:
        type: string
        pattern: ^[a-zA-Z0-9-]+$
        description: Financial Year for which the KPI is applicable
      documents:
        type: array
        items:
          $ref: "#/definitions/Document"
      createdBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who created the record
      lastModifiedBy: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: User ID of the User who last updated the record
      createdDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record got created
      lastModifiedDate: 
        type: integer
        format: int64
        pattern: ^[0-9]+$
        description: Date on which the record for modified
    required:
      - name
      - code
      - finYear
      
     
  KPIRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      KPI:
        $ref: '#/definitions/KPI'
    required:
      - requestInfo
      - KPI
      
  KPIResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      KPI:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KPI'
      
  KPITargetRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      kpiTarget:
        $ref: '#/definitions/KpiTarget'
    required:
      - requestInfo
      - kpiTarget
  
  KPITargetResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      kpiTargets:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiTarget'
    
  KPIValueRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      kpiValue:
        $ref: '#/definitions/KpiValue'
    required:
      - requestInfo
      - kpiValue
      
  KPIValueResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      kpiValues:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValue'
        
  KPIValueSearchRequest:
    type: object
    properties:
      requestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
      kpiCodes:
        type: array
        items:
          type: string
      tenantId:
        type: array
        items:
          type: string
      finYear:
        type: array
        items:
          type: string
          
  KPIValueSearchResponse:
    type: object
    properties:
      responseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      kpiValuesList:
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/KpiValueList'
    
       
parameters:

  name:
    name: KPI Name
    in: query
    description: Name of the KPI
    required: false
    type: string

  code:
    name: KPI Code
    in: query
    description: Code of the KPI
    required: false
    type: string
    minLength: 0
    maxLength: 64
    
  kpiId:
    name: Unique KPI ID
    in: query
    description: ID of the KPI
    required: false
    type: string 
  
  pageSize:
    name: pageSize
    in: query
    description: Number of records returned.
    type: integer
    minimum: 0
    exclusiveMinimum: true
    maximum: 100
    exclusiveMaximum: false
    multipleOf: 10
    default: 20

  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
    default: 1

  sortResult:
    name: sort
    in: query
    description: Connections results will be sorted by createdTime ascending by default if this parameter is not provided.
    type: array
    uniqueItems: true
    minItems: 1
    maxItems: 4
    collectionFormat: pipes
    items:
      type: string
      pattern: '[-+](name|mobileNumber|locality|consumerNumber)'
    default:
      - +name