serviceMaps:
 serviceName: Financial Bill Service
 mappings:
 - version: 1.0
   name: bill create
   description: create bills in egf_billregister
   fromTopic: egf-bill-billregister-save-topic
   queryMaps: 
    - query: INSERT INTO egf_billregister( tenantid, billtype, billsubtype, billnumber, billdate, billamount, passedamount, modulename, status, fund, function, fundsource, scheme, subscheme, functionary, location, department, sourcepath, budgetcheckrequired, budgetappropriationno, partybillnumber, partybilldate, description, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*
      jsonMaps:
       
       - jsonPath: $.billRegisters.*.tenantId
         
       - jsonPath: $.billRegisters.*.billType
         
       - jsonPath: $.billRegisters.*.billSubType

       - jsonPath: $.billRegisters.*.billNumber
       
       - jsonPath: $.billRegisters.*.billDate
         dbType: LONG

       - jsonPath: $.billRegisters.*.billAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.passedAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.moduleName

       - jsonPath: $.billRegisters.*.status.code

       - jsonPath: $.billRegisters.*.fund.code

       - jsonPath: $.billRegisters.*.function.code

       - jsonPath: $.billRegisters.*.fundsource.code

       - jsonPath: $.billRegisters.*.scheme.code

       - jsonPath: $.billRegisters.*.subScheme.code

       - jsonPath: $.billRegisters.*.functionary.code

       - jsonPath: $.billRegisters.*.location.code

       - jsonPath: $.billRegisters.*.department.code

       - jsonPath: $.billRegisters.*.sourcePath

       - jsonPath: $.billRegisters.*.budgetCheckRequired

       - jsonPath: $.billRegisters.*.budgetAppropriationNo

       - jsonPath: $.billRegisters.*.partyBillNumber

       - jsonPath: $.billRegisters.*.partyBillDate
         dbType: LONG

       - jsonPath: $.billRegisters.*.description

       - jsonPath: $.billRegisters.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.auditDetails.lastModifiedTime
         dbType: LONG

    - query: INSERT INTO egf_billdetail(tenantId, id, orderid, chartofaccount, debitamount, creditamount, function, bill, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*.billDetails.*
      jsonMaps:

       - jsonPath: $.billRegisters.*.billDetails.*.tenantId
       
       - jsonPath: $.billRegisters.*.billDetails.*.id

       - jsonPath: $.billRegisters.*.billDetails.*.orderId
         dbType: INTEGER
         
       - jsonPath: $.billRegisters.*.billDetails.*.chartOfAccount.glcode

       - jsonPath: $.billRegisters.*.billDetails.*.debitAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails.*.creditAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails.*.function.code

       - jsonPath: $.billRegisters[?({id} in @.billDetails[*].id)].billNumber
         
       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.lastModifiedTime
         dbType: LONG

    - query: INSERT INTO egf_billpayeedetail(tenantId, id, accountdetailtype, accountdetailkey, amount, billdetail, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*.billDetails.*.billPayeeDetails.*
      jsonMaps:

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.tenantId
       
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.id

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.accountDetailType.id
         
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.accountDetailKey.id

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.amount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails[?({id} in @.billPayeeDetails[*].id)].id
         
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.lastModifiedTime
         dbType: LONG

    - query: INSERT INTO egf_billchecklist(tenantId, id, bill, checklist, checklistvalue, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*.checkLists.*
      jsonMaps:

       - jsonPath: $.billRegisters.*.checkLists.*.tenantId
       
       - jsonPath: $.billRegisters.*.checkLists.*.id

       - jsonPath: $.billRegisters[?({id} in @.checkLists[*].id)].billNumber

       - jsonPath: $.billRegisters.*.checkLists.*.checklist.code

       - jsonPath: $.billRegisters.*.checkLists.*.checklistValue
         
       - jsonPath: $.billRegisters.*.checkLists.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.checkLists.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.checkLists.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.checkLists.*.auditDetails.lastModifiedTime
         dbType: LONG


 - version: 1.0
   name: bill update
   description: update bills in egf_billregister
   fromTopic: egf-bill-billregister-update-topic
   queryMaps: 
    - query: update egf_billregister set billtype=? , billsubtype=? , billdate=? , billamount=? , passedamount=? , modulename=? , status=? , fund=? , function=? , fundsource=? , scheme=? , subscheme=? , functionary=? , location=? , department=? , sourcepath=? , budgetcheckrequired=? , budgetappropriationno=? , partybillnumber=? , partybilldate=? , description=? ,lastmodifiedby=? , lastmodifiedtime=? where tenantId=? and billNumber=?;
      basePath: $.billRegisters.*
      jsonMaps:
       
       - jsonPath: $.billRegisters.*.billType
         
       - jsonPath: $.billRegisters.*.billSubType

       - jsonPath: $.billRegisters.*.billDate
         dbType: LONG

       - jsonPath: $.billRegisters.*.billAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.passedAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.moduleName

       - jsonPath: $.billRegisters.*.status.code

       - jsonPath: $.billRegisters.*.fund.code

       - jsonPath: $.billRegisters.*.function.code

       - jsonPath: $.billRegisters.*.fundsource.code

       - jsonPath: $.billRegisters.*.scheme.code

       - jsonPath: $.billRegisters.*.subScheme.code

       - jsonPath: $.billRegisters.*.functionary.code

       - jsonPath: $.billRegisters.*.location.code

       - jsonPath: $.billRegisters.*.department.code

       - jsonPath: $.billRegisters.*.sourcePath

       - jsonPath: $.billRegisters.*.budgetCheckRequired

       - jsonPath: $.billRegisters.*.budgetAppropriationNo

       - jsonPath: $.billRegisters.*.partyBillNumber

       - jsonPath: $.billRegisters.*.partyBillDate
         dbType: LONG

       - jsonPath: $.billRegisters.*.description

       - jsonPath: $.billRegisters.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.auditDetails.lastModifiedTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.tenantId

       - jsonPath: $.billRegisters.*.billNumber

    - query: INSERT INTO egf_billdetail(tenantId, id, orderid, chartofaccount, debitamount, creditamount, function, bill, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*.billDetails.*
      jsonMaps:

       - jsonPath: $.billRegisters.*.billDetails.*.tenantId
       
       - jsonPath: $.billRegisters.*.billDetails.*.id

       - jsonPath: $.billRegisters.*.billDetails.*.orderId
         dbType: INTEGER
         
       - jsonPath: $.billRegisters.*.billDetails.*.chartOfAccount.glcode

       - jsonPath: $.billRegisters.*.billDetails.*.debitAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails.*.creditAmount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails.*.function.code

       - jsonPath: $.billRegisters[?({id} in @.billDetails[*].id)].billNumber
         
       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.billDetails.*.auditDetails.lastModifiedTime
         dbType: LONG

    - query: INSERT INTO egf_billpayeedetail(tenantId, id, accountdetailtype, accountdetailkey, amount, billdetail, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.billRegisters.*.billDetails.*.billPayeeDetails.*
      jsonMaps:

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.tenantId
       
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.id

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.accountDetailType.id
         
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.accountDetailKey.id

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.amount
         dbType: DOUBLE

       - jsonPath: $.billRegisters.*.billDetails[?({id} in @.billPayeeDetails[*].id)].id
         
       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.createdBy

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.createdTime
         dbType: LONG

       - jsonPath: $.billRegisters.*.billDetails.*.billPayeeDetails.*.auditDetails.lastModifiedTime
         dbType: LONG
