spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/test_scheduler_datasync
      username: erp_owner
      password: erp_owner
    profiles:
      active: "ms-to-ml"

flyway:
  user: erp_owner
  password: erp_owner
  outOfOrder: true
  table: data_sync_schema_version
  baseline-on-migrate: true
  url: jdbc:postgresql://localhost:5432/test_scheduler_datasync
  locations: db/migration/ddl,db/migration/seed

state: ap
rateInSeconds: 5000

---
source-schemas: kurnool
destination-schema: microservice

spring:
  profiles: ml-to-ms
sync:
  info:
    - sourceTable: eg_hierarchy_type
      destinationTable: eg_hierarchy_type
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: createddate
          destination: createddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: lastmodifieddate
          destination: lastmodifieddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: createdby
          destination: createdby
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifiedby
          destination: lastmodifiedby
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: version
          destination: version
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: localname
          destination: localname
          Type: String
          shouldSource: True
          shouldSync: True

    - sourceTable: eg_boundary_type
      destinationTable: eg_boundary_type
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: hierarchy
          destination: hierarchy
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: parent
          destination: parent
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: isactive
          destination: active
          Type: Boolean
          shouldSource: True
          shouldSync: True

    - sourceTable: bank
      destinationTable: egf_bank
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: isactive
          destination: active
          Type: Boolean
          shouldSource: True
          shouldSync: True

    - sourceTable: bankbranch
      destinationTable: egf_bankbranch
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: branchcode
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: branchname
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: isactive
          destination: active
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: bankid
          destination: bankid
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: branchaddress1
          destination: address
          Type: String
          shouldSource: True
          shouldSync: True

---
source-schemas: microservice
destination-schema: NA
spring:
  profiles: ms-to-ml
sync:
  info:
    - sourceTable: egf_bank
      destinationTable: bank
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: active
          destination: isactive
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

    - sourceTable: egf_bankbranch
      destinationTable: bankbranch
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: code
          destination: branchcode
          Type: String
          shouldSource: True
          shouldSync: True

        - source: name
          destination: branchname
          Type: String
          shouldSource: True
          shouldSync: True

        - source: active
          destination: isactive
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: bankid
          destination: bankid
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: address
          destination: branchaddress1
          Type: String
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

        - source: NA
          destination: branchFax
          Type: String
          shouldSource: False
          shouldSync: True
          defaultValue: Test
