spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/test_scheduler_datasync
      username: erp_owner
      password: erp_owner
    profiles:
      active: "ms-to-ml"

flyway:
  user: erp_owner
  password: erp_owner
  outOfOrder: true
  table: data_sync_schema_version
  baseline-on-migrate: true
  url: jdbc:postgresql://localhost:5432/test_scheduler_datasync
  locations: db/migration/ddl,db/migration/seed

state: ap
rateInSeconds: 5000

---
source-schemas: kurnool,adoni
destination-schema: microservice

spring:
  profiles: ml-to-ms
sync:
  info:
    - sourceTable: eg_department
      destinationTable: eg_department
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: NA
          destination: active
          Type: Boolean
          shouldSource: False
          shouldSync: True
          defaultValue: 1


    - sourceTable: eg_designation
      destinationTable: egeis_designation
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: description
          destination: description
          Type: String
          shouldSource: True
          shouldSync: True

        - source: chartofaccounts
          destination: chartofaccounts
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: NA
          destination: active
          Type: Boolean
          shouldSource: False
          shouldSync: True
          defaultValue: 1

    - sourceTable: egeis_deptdesig
      destinationTable: egeis_departmentdesignation
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: department
          destination: departmentid
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: designation
          destination: designationid
          Type: Integer
          shouldSource: True
          shouldSync: True

    - sourceTable: eg_position
      destinationTable: egeis_position
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          type: String
          shouldSource: True
          shouldSync: True

        - source: deptdesig
          destination: deptdesigid
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: ispostoutsourced
          destination: ispostoutsourced
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: NA
          destination: active
          Type: Boolean
          shouldSource: False
          shouldSync: True
          defaultValue: 1

#    - sourceTable: bank
#      destinationTable: egf_bank
#      sourceTimeZone: UTC
#      columns:
#        - source: id
#          destination: id
#          type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: code
#          destination: code
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: name
#          destination: name
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: isactive
#          destination: active
#          Type: Boolean
#          shouldSource: True
#          shouldSync: True
#
#    - sourceTable: bankbranch
#      destinationTable: egf_bankbranch
#      sourceTimeZone: UTC
#      columns:
#        - source: id
#          destination: id
#          type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: branchcode
#          destination: code
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: branchname
#          destination: name
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: isactive
#          destination: active
#          Type: Boolean
#          shouldSource: True
#          shouldSync: True
#
#        - source: bankid
#          destination: bankid
#          Type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: branchaddress1
#          destination: address
#          Type: String
#          shouldSource: True
#          shouldSync: True

---
source-schemas: microservice
destination-schema: NA
spring:
  profiles: ms-to-ml
sync:
  info:
    - sourceTable: eg_user
      destinationTable: eg_user
      sourceTimeZone: Asia/Kolkata
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: title
          destination: title
          Type: String
          shouldSource: True
          shouldSync: True

        - source: salutation
          destination: salutation
          Type: String
          shouldSource: True
          shouldSync: True

        - source: dob
          destination: dob
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: locale
          destination: locale
          Type: String
          shouldSource: True
          shouldSync: True

        - source: username
          destination: username
          Type: String
          shouldSource: True
          shouldSync: True

        - source: password
          destination: password
          Type: String
          shouldSource: True
          shouldSync: True

        - source: pwdexpirydate
          destination: pwdexpirydate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: mobilenumber
          destination: mobilenumber
          Type: String
          shouldSource: True
          shouldSync: True

        - source: altcontactnumber
          destination: altcontactnumber
          Type: String
          shouldSource: True
          shouldSync: True

        - source: emailid
          destination: emailid
          Type: String
          shouldSource: True
          shouldSync: True

        - source: createddate
          destination: createddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: lastmodifieddate
          destination: lastmodifieddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: createdby
          destination: createdby
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifiedby
          destination: lastmodifiedby
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: active
          destination: active
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: name
          destination: name
          Type: String
          shouldSource: True
          shouldSync: True

        - source: gender
          destination: gender
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: pan
          destination: pan
          Type: String
          shouldSource: True
          shouldSync: True

        - source: aadhaarnumber
          destination: aadhaarnumber
          Type: String
          shouldSource: True
          shouldSync: True

        - source: type
          destination: type
          Type: String
          shouldSource: True
          shouldSync: True

        - source: version
          destination: version
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: guardian
          destination: guardian
          Type: String
          shouldSource: True
          shouldSync: True

        - source: guardianrelation
          destination: guardianrelation
          Type: String
          shouldSource: True
          shouldSync: True

        - source: signature
          destination: signature
          Type: String
          shouldSource: True
          shouldSync: True

        - source: accountlocked
          destination: accountlocked
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

    - sourceTable: egeis_employee
      destinationTable: egeis_employee
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: code
          destination: code
          Type: String
          shouldSource: True
          shouldSync: True

        - source: dateofappointment
          destination: dateofappointment
          Type: Date
          shouldSource: True
          shouldSync: True

        - source: dateofretirement
          destination: dateofretirement
          Type: Date
          shouldSource: True
          shouldSync: True

        - source: employeetypeid
          destination: employeetype
          Type: Date
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

    - sourceTable: egeis_assignment
      destinationTable: egeis_assignment
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: fundid
          destination: fund
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: functionid
          destination: function
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: designationid
          destination: designation
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: functionaryid
          destination: functionary
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: departmentid
          destination: department
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: positionid
          destination: position
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: gradeid
          destination: grade
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifiedby
          destination: lastmodifiedby
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifieddate
          destination: lastmodifieddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: createddate
          destination: createddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: createdby
          destination: createdby
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: fromdate
          destination: fromdate
          Type: Date
          shouldSource: True
          shouldSync: True

        - source: todate
          destination: todate
          Type: Date
          shouldSource: True
          shouldSync: True

        - source: NA
          destination: version
          Type: Integer
          shouldSource: False
          shouldSync: True
          defaultValue: 0

        - source: employeeid
          destination: employee
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: isprimary
          destination: isprimary
          Type: Boolean
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

    - sourceTable: egeis_hoddepartment
      destinationTable: egeis_employee_hod
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: departmentid
          destination: hod
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: assignmentid
          destination: assignment
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifieddate
          destination: lastmodifieddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

    - sourceTable: egeis_employeejurisdictions
      destinationTable: egeis_jurisdiction
      sourceTimeZone: UTC
      columns:
        - source: id
          destination: id
          type: Integer
          shouldSource: True
          shouldSync: True

        - source: employeeid
          destination: employee
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: jurisdictionid
          destination: boundary
          Type: Integer
          shouldSource: True
          shouldSync: True

        - source: lastmodifieddate
          destination: lastmodifieddate
          Type: TimestampWithoutTimeZone
          shouldSource: True
          shouldSync: True

        - source: tenantid
          destination: NA
          Type: String
          shouldSource: True
          shouldSync: False

#    - sourceTable: egf_bank
#      destinationTable: bank
#      sourceTimeZone: UTC
#      columns:
#        - source: id
#          destination: id
#          type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: code
#          destination: code
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: name
#          destination: name
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: active
#          destination: isactive
#          Type: Boolean
#          shouldSource: True
#          shouldSync: True
#
#        - source: tenantid
#          destination: NA
#          Type: String
#          shouldSource: True
#          shouldSync: False
#
#    - sourceTable: egf_bankbranch
#      destinationTable: bankbranch
#      sourceTimeZone: UTC
#      columns:
#        - source: id
#          destination: id
#          type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: code
#          destination: branchcode
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: name
#          destination: branchname
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: active
#          destination: isactive
#          Type: Boolean
#          shouldSource: True
#          shouldSync: True
#
#        - source: bankid
#          destination: bankid
#          Type: Integer
#          shouldSource: True
#          shouldSync: True
#
#        - source: address
#          destination: branchaddress1
#          Type: String
#          shouldSource: True
#          shouldSync: True
#
#        - source: tenantid
#          destination: NA
#          Type: String
#          shouldSource: True
#          shouldSync: False
#
#        - source: NA
#          destination: branchFax
#          Type: String
#          shouldSource: False
#          shouldSync: True
#          defaultValue: Test
