# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: Employee Information System APIs- Attendance
  description: All APIs related to employee attendance are listed here.
  contact:
    name: Elzan Mathew
externalDocs: 
  description: Complete documentation describing how to use this API
  url: http://182.74.137.193/docs/products/eGov%20EIS/ProdSpecs/eGov%20EIS_PSD_OS.doc
# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /attendances:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown 
      summary: Get the list of attendances for any date for any employee based on the input.
      description: |
        Get the attendance list based on the input parameters. If one need attendance for month, then pass month and year, if one needs for a certain date, then pass only the applicable_on.
      # This is array of GET operation parameters:
      parameters:
        - name: request_info
          in: body
          description: Commmon request info for getting attendance.
          required: true
          schema:
            $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/RequestInfo'
        - name: applicable_on
          in: query
          required: false
          description: The date for which the attendance is needed.
          type: string
          format: date
        - name: month
          in: query
          required: false
          description: The month for which the attendance is needed.
          type: string
        - name: year
          in: query
          required: false
          description: The calander year name for which the attendance is needed.
          type: string
        - name: code
          in: query
          required: false
          description: The employee's code for whom the attendance is requested.
          type: string
          minLength: 0
          maxLength: 256
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: department_code
          in: query
          description: Department code for which the employee belongs to as primary assignment.
          required: false
          type: string
          format: varchar
          minLength: 0
          maxLength: 256
          exclusiveMinimum: true
          exclusiveMaximum: false
        - name: designation_code
          in: query
          description: Designation code for which the employee belongs to as primary assignment.
          required: false
          type: string
          format: varchar
          minLength: 0
          maxLength: 256
          exclusiveMinimum: true
          exclusiveMaximum: false
        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/pageSize"
        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/pageNumber"
        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/tenantId"
        - $ref: "#/parameters/sortAttendance"
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: "#/definitions/AttendanceRes"
 
        '400':
          description: Invalid input.
          schema:
            $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/ErrorRes'
        '404':
          $ref: "#/responses/AttendanceDoesNotExistResponse"
      tags: 
       - Attendance
       
    post:
      summary: Create a new attendance data for an employee or set of employees for any given date or date range.
      description: This API will be used to create an attendance data for employee(s) for a given date(s).
      parameters:
        - name: attendance
          in: body
          description: Details for the new attendance.
          required: true
          schema:
            $ref: '#/definitions/AttendanceReq'

        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/tenantId"
        - $ref: '#/parameters/sortAttendance'
      tags:
        - Attendance
      responses:
        '201':
          description: Attendance created sucessfully.
          schema:
            $ref: '#/definitions/AttendanceRes'
        '400':
          description: Invalid Input.

  /attendances/{employee_code}:  
    parameters:
      - $ref: "#/parameters/code"
    put:
      summary: Update attendance data for a particular employee on a particular date or for any number of days.
      description: Any employee's attendance can be modified for a given date or for mutlipe days using this API.
      parameters:
        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/tenantId"
        - name: attendance
          in: body
          description: Request header for the attendance with new of values.
          required: true
          schema:
            $ref: '#/definitions/AttendanceReq'
      tags:
        - Attendance
      responses:
        '200':
          description: Attendance updated.
          schema:
            $ref: '#/definitions/AttendanceRes'
        '400':
          description: Invalid input.
          schema:
            $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/ErrorRes'
        '404':
          $ref: "#/responses/EmployeeDoesNotExistResponse"
         
    delete:
      summary: Delete the attendance data for the employee code passed for any number of days.
      description: Attendance data for an employee for any specified dates can be removed using this API.
      parameters:
        - $ref: "http://localhost:8081/swagger-yaml/eis-commons.yaml/#/parameters/tenantId"
        - name: attendance
          in: body
          description: Request header for the attendance to be deleted
          required: true
          schema:
            $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/RequestInfo'
      tags:
        - Attendance
      responses:
        '204':
          description: Attendance deleted.
        '400':
          description: Invalid input.
          schema:
            $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/ErrorRes'
        '404':
          $ref: "#/responses/EmployeeDoesNotExistResponse"



definitions:
  Attendance:
    title: Attendance of an employee
    description: Employee attendance will be marked day wise. Holidays will be marked as `H` and present will be marked as `P`.
    type: object
    properties:
      id:
       type: integer
       format: int64
       description : Unique identifier of the attendance.
      date:
        type: string
        format: date
        description: Date of attendance of the employee.
      employee:
        type: string
        description: Employee code to whom this attendance data belongs to.
      month:
        type: string 
        description: The month for which this attendance belongs to.
      year:
        type: string
        description: Calander year for which this attendance belongs to.
      type:
        type: object
        description: |
        
          The attendance type applicable to this employee as on this date, based on if he/she was on leave or absent or holiday etc. Various types available in the system are-
          
          type  | definition
          ----- |-----------
              1 |Present
              2	|Absent
              3 |CompOff
              4	|LeavePaid
              5	|HalfPresent
              6	|HalfLeavePaid
              7	|TwoHalfLeavesPaid
              8	|LeaveUnpaid
              9	|HalfLeaveUnpaid
              10|TwoHalfLeavesUnpaid
              11|OverTime
              12|CompOffElligibe
              13|Holiday

        items:
         $ref: "#/definitions/AttendanceType"
      remarks:
        type: string
        description: any general remark regarding that day attendance.
      createdBy:
        type: integer
        format: int64
        description: Id of the user who created the record. 
      createdDate:
        type: string
        format: date
        description: Date on which the role master data was added into the system.
      lastModifiedBy:
        type: integer
        format: int64
        description: Id of the user who last modified the record. 
      lastModifiedDate:
        type: string
        format: date
        description: Date on which the role master data was last modified.
    required:
      - id
      - date
      - employee
      - month
      - year
      - type
      - createdDate
      - createdBy
  
  AttendanceType:
    description: This is a set up object which contains the different types of attendance marking that is possible in the system. Based on holiday, present, leave etc, the value will change.
    properties:
      id:
       type: integer
       format: int64
       description : Unique identifier of the attendance.
      code:
        type: string
        description: The unique code to identify the attendance type.
      description:
        type: string
        description: The description of the attendance type.
    required:
      - id
      - code
      - description

  AttendanceReq:
    type: object
    properties:
      RequestInfo:
        $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/RequestInfo'
      Attendance:
        type: array
        items:
          $ref: '#/definitions/Attendance'

  AttendanceRes:
    type: object
    properties:
      ResponseInfo:
        $ref: 'http://localhost:8081/swagger-yaml/eis-commons.yaml/#/definitions/ResponseInfo'
      Attendance:
        type: array
        items:
          $ref: '#/definitions/Attendance'
          

parameters:
  code:
    name: employee_code
    in: path
    required: true
    description: The employee's code.
    type: string
    minLength: 0
    maxLength: 256
    exclusiveMinimum: true
    exclusiveMaximum: false
    


  sortAttendance:
    name: sort
    in: query
    description: Result will be sorted by date and employee code ascending by default if this parameter is not provided.
    type: array
    uniqueItems: true
    minItems: 1
    maxItems: 3
    collectionFormat: pipes
    items:
      type: string
      pattern: '[-+](date|employee|type)'
    default:
      - +date
      - +employee
      

#  $ref: http://localhost:8081/swagger-yaml/leave.yaml
responses:
  EmployeeDoesNotExistResponse:
    description: Employee does not exist.
  AttendanceDoesNotExistResponse:
    description: Attendance does not exist.
tags:
  - name: Attendance
    description: Everything you need to handle Employee attendance.

