serviceConfigs:
 - serviceCode: PT_NODUES
   searchDemand:
    url: http://egov-micro-dev.egovernments.org/billing-service/demand/_search
    queryAppend:
       - tenantId :$.serviceReq.attributeValues[0].value
    result: 
       - $..Demands.length()
       - $..demandDetails[?(@.taxAmount >= @.collectionAmount)]           
    generateId:
      url: http://egov-micro-dev.egovernments.org/egov-idgen/id/_generate
      request: {"requestInfo": $.requestInfo,"idRequests":[{"idName":"CS.ServiceRequest","tenantId":$.serviceReq.tenantId,"format":"SRN-[cy:MM]/[fy:yyyy-yy]-[d{4}]"}]}
      result: $.idResponses[0].id
    
    applicationFee: 100

 - serviceCode: PT_EXTRACT
   searchDemand:
    url: /billing-service/demand/_search?tenantId=$.tenantId&businessService=PT
    queryAppend:
     - consumerCode:$.serviceReq.attributeValues[0]
     - mobile:$.serviceReq.attributeValues[1]
     - email:$.serviceReq.attributeValues[2]
    result:   
      - $..demandDetails[?(@.taxAmount >= @.collectionAmount)] 
    generateId:
      url: http://egov-micro-dev.egovernments.org/egov-idgen/id/_generate
      request: {"requestInfo": $.requestInfo,"idRequests":[{"idName":"CS.ServiceRequest","tenantId":$.serviceReq.tenantId,"format":"SRN-[cy:MM]/[fy:yyyy-yy]-[d{4}]"}]}
      result: $.idResponses[0].id  
    applicationFee: 100

 - serviceCode: WATER_NODUES
   searchDemand:
    url: /billing-service/demand/_search?tenantId=$.tenantId&businessService=WC
    queryAppend:
     - consumerCode:$.serviceReq.attributeValues[0]
     - mobile:$.serviceReq.attributeValues[1]
     - email:$.serviceReq.attributeValues[2]
    result:
      - $..demandDetails[?(@.taxAmount >= @.collectionAmount)] 
    generateId:
      url: http://egov-micro-dev.egovernments.org/egov-idgen/id/_generate
      request: {"requestInfo": $.requestInfo,"idRequests":[{"idName":"CS.ServiceRequest","tenantId":$.serviceReq.tenantId,"format":"SRN-[cy:MM]/[fy:yyyy-yy]-[d{4}]"}]}
      result: $.idResponses[0].id  
    applicationFee: 100