---
ReportDefinitions:
  #  Stock Opening Balance Report
- reportName: openingBalanceReport
  summary: Stock Opening Balance Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: financialyear
    label: inventory.financialYear
    type: string
    source: materialReceipt

  - name: storeName
    label: inventory.store.name
    type: string
    source: materialReceipt

  - name: materialCode
    label: inventory.material.code
    type: string
    source: materialReceipt

  - name: materialName
    label: inventory.materialName
    type: string
    source: material

  - name: materialTypeName
    label: inventory.material.materialtype
    type: string
    source: materialReceiptDetails

  - name: uom
    label: reports.inventory.openbal.Uom
    type: string
    source: materialReceiptDetails

  - name: qty
    label: reports.inventory.openbal.Qty.
    type: string
    source: materialReceiptDetails

  - name: rate
    label: inventory.Rate
    type: string
    source: materialReceiptDetails

  - name: totalAmount
    label: reports.inventory.openbal.TotalAmount
    type: string
    source: materialReceiptDetails

  - name: remarks
    label: reports.inventory.openbal.Remarks
    type: string
    source: materialReceiptDetails

  searchParams:
  - name: financialYear
    label: inventory.financialYear
    type: singlevaluelist
    pattern: 'list://2011:2011,2012:2012,2013:2013,2014:2014,2015:2015,2016:2016,2017:2017,2018:2018,2019:2019'
    source: materialReceipt
    isMandatory: true

  - name: storeName
    label: inventory.store.name
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?tenantId=$tenantid|$..code|$..name
    source: store
    isMandatory: true

  - name: materialTypeName
    label: inventory.material.materialtype
    type: string
    source: materialReceipt
    isMandatory: false
    searchClause: AND matrcpt.receiptType = $materialTypeName

  - name: materialName
    label: inventory.materialName
    type: string
    source: materialReceipt
    isMandatory: false
    searchClause: AND mat.name = $materialName

  query:  SELECT matrcpt.financialyear as financialyear,matrcpt.receivingstore as storeName,matrcptdtl.material as materialcode,matrcpt.receiptType as materialtypename,matrcptdtl.uomno as uom,
          matrcptdtl.receivedqty as qty,matrcptdtl.unitrate as rate,(matrcptdtl.unitrate * matrcptdtl.receivedqty) as totalamount,matrcptdtl.remarks as remarks FROM materialreceipt matrcpt,
          materialreceiptdetail matrcptdtl WHERE matrcpt.financialyear = $financialyear AND matrcpt.receipttype ='OPENING BALANCE' AND matrcpt.tenantid= $tenantId AND matrcpt.tenantid=matrcptdtl.tenantid
          AND matrcpt.mrnnumber = matrcptdtl.mrnnumber

#  Supplier Report
- reportName: supplierreport
  summary: Supplier Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:
  - name: supplierCode
    label: inventory.supplier.code
    type: string
    source: supplier

  - name: supplierType
    label: inventory.supplier.type
    type: string
    source: supplier

  - name: supplierName
    label: inventory.supplier.name
    type: string
    source: supplier

  - name: status
    label: inventory.common.status
    type: string
    source: supplier

  - name: address
    label: inventory.supplier.address
    type: string
    source: supplier

  - name: contactno
    label: inventory.common.contactNo
    type: string
    source: supplier

  - name: email
    label: inventory.report.email
    type: string
    source: supplier

  - name: cstNo
    label: inventory.common.cstno
    type: string
    source: supplier

  - name: bankName
    label: inventory.common.bankname
    type: string
    source: supplier

  - name: bankAcctNo
    label: inventory.common.bankacctno
    type: string
    source: supplier

  - name: ifsc
    label: inventory.common.ifsc
    type: string
    source: supplier

  - name: contactPerson
    label: inventory.common.contactperson
    type: string
    source: supplier

  - name: contactPersonNo
    label: inventory.common.contactpersonno
    type: string
    source: supplier

  query:  select code as supplierCode, type as supplierType, name as supplierName, status,
          address, contactno, email, cstno, bankcode as bankName, bankacctno,
          bankifsc as ifsc, contactperson, contactpersonno
          from supplier as supplier
          where tenantid = $tenantid
          order by supplier.name asc;
