---
ReportDefinitions:
  #  Stock Opening Balance Report
- reportName: openingBalanceReport
  summary: Stock Opening Balance Report
  version: 1.0.0
  moduleName: inventory
  externalService:
  - entity: $.MdmsRes.inventory.Material
    apiURL: http://egov-micro-dev.egovernments.org/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=inventory&masterName=Material
    keyOrder: code,name,tenantId
    tableName: tbl_material
  sourceColumns:

  - name: financialYear
    label: inventory.financialYear
    type: string
    source: materialReceipt

  - name: storeName
    label: inventory.store.name
    type: string
    source: materialReceipt

  - name: materialCode
    label: inventory.material.code
    type: string
    source: materialReceipt

  - name: materialName
    label: inventory.materialName
    type: string
    source: material

  - name: materialTypeName
    label: inventory.material.materialtype
    type: string
    source: materialReceiptDetails

  - name: uom
    label: reports.inventory.openbal.Uom
    type: string
    source: materialReceiptDetails

  - name: qty
    label: reports.inventory.openbal.Qty.
    type: string
    source: materialReceiptDetails

  - name: rate
    label: inventory.Rate
    type: string
    source: materialReceiptDetails

  - name: totalAmount
    label: reports.inventory.openbal.TotalAmount
    type: string
    source: materialReceiptDetails

  - name: remarks
    label: reports.inventory.openbal.Remarks
    type: string
    source: materialReceiptDetails

  searchParams:
  - name: financialYear
    label: inventory.financialYear
    type: singlevaluelist
    pattern: 'list://2017-2018:2017-2018'
    source: materialReceipt
    isMandatory: true

  - name: storeName
    label: inventory.store.name
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?active=true&tenantId=$tenantid|$..code|$..name
    source: store
    isMandatory: true
    wrapper: true

  - name: materialTypeName
    label: inventory.material.materialtype
    type: singlevaluelist
    pattern: 'list://OPENING BALANCE:OPENING BALANCE'
    source: materialReceipt
    isMandatory: false
    searchClause: AND matrcpt.receiptType = $materialTypeName

  - name: materialName
    label: inventory.materialName
    type: string
    source: materialReceipt
    isMandatory: false
    searchClause: AND mat.name = $materialName

  query:  SELECT matrcpt.financialyear as financialyear,
          store.name as storeName,
          matrcptdtl.material as materialcode,
          mat.name as materialname,
          matrcpt.receiptType as materialtypename,
          matrcptdtl.uomno as uom,
          matrcptdtl.receivedqty as qty,
          matrcptdtl.unitrate as rate,
          (matrcptdtl.unitrate * matrcptdtl.receivedqty) as totalamount,
          matrcptdtl.remarks as remarks 
          FROM materialreceipt matrcpt,
          (VALUES tbl_material) as mat (code, name, tenantid),
          materialreceiptdetail matrcptdtl , store store 
          WHERE matrcpt.financialyear = $financialYear 
          AND matrcpt.receivingstore =  store.code
          AND matrcpt.receivingstore = $storeName 
          and store.tenantid = matrcpt.tenantid
          AND matrcpt.tenantid = matrcptdtl.tenantid
          AND mat.tenantid = matrcpt.tenantid 
          AND matrcpt.tenantid = $tenantid 
          AND matrcpt.mrnnumber = matrcptdtl.mrnnumber 
          AND mat.code = matrcptdtl.material

#  Supplier Report
- reportName: supplierreport
  summary: Supplier List
  version: 1.0.0
  moduleName: inventory
  sourceColumns:
  - name: supplierCode
    label: inventory.supplier.code
    type: string
    source: supplier

  - name: supplierType
    label: inventory.supplier.type
    type: string
    source: supplier

  - name: supplierName
    label: inventory.supplier.name
    type: string
    source: supplier

  - name: status
    label: inventory.common.status
    type: string
    source: supplier

  - name: address
    label: inventory.supplier.address
    type: string
    source: supplier

  - name: contactNo
    label: inventory.common.contactNo
    type: string
    source: supplier

  - name: email
    label: inventory.report.email
    type: string
    source: supplier

  - name: cstNo
    label: inventory.common.cstno
    type: string
    source: supplier

  - name: bankName
    label: inventory.common.bankname
    type: string
    source: supplier

  - name: bankBranch
    label: inventory.common.bankbranchname
    type: string
    source: supplier

  - name: bankAcctNo
    label: inventory.common.bankacctno
    type: string
    source: supplier

  - name: ifsc
    label: inventory.common.ifsc
    type: string
    source: supplier

  - name: contactPerson
    label: inventory.common.contactperson
    type: string
    source: supplier

  - name: contactPersonNo
    label: inventory.common.contactpersonno
    type: string
    source: supplier

  query:  select supplier.code as supplierCode, supplier.type as supplierType, supplier.name as supplierName,
          supplier.status as status, supplier.address as address , supplier.contactno as contactNo,
          supplier.email as email, supplier.cstno as cstNo,
          bank.name as bankName, supplier.bankbranch as bankBranch, supplier.bankacctno as bankAcctNo,
          supplier.bankifsc as ifsc, supplier.contactperson as contactPerson,
          supplier.contactpersonno as contactPersonNo
          from supplier as supplier, egf_bank bank
          where
          bank.code = supplier.bankcode
          and bank.tenantid = supplier.tenantid
          and supplier.tenantid = $tenantid
          order by supplier.name asc;

# Material Returned Report
# Need to change  drop down Link based on report and Query
- reportName: materialReturnedReport
  summary: Material Returned Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: materialReturnNo
    label: inventory.materialReturnNo
    type: string
    source: inventory

  - name: returnDate
    label: inventory.returnDate
    type: string
    source: inventory

  - name: supplierName
    label: inventory.supplierName
    type: epoch
    source: inventory

  - name: materialCode
    label: inventory.materialCode
    type: string
    source: inventory

  - name: materialName
    label: inventory.materialName
    type: string
    source: inventory

  - name: returnedQty
    label: inventory.returnedQty
    type: string
    source: inventory

  - name: uom
    label: inventory.uom
    type: string
    source: inventory

  - name: unitRate
    label: inventory.unitRate
    type: string
    source: inventory

  - name: totalReturnedAmount
    label: inventory.totalReturnedAmount
    type: string
    source: inventory

  - name: returnRemarks
    label: inventory.returnRemarks
    type: string
    source: inventory

  - name: returnBy
    label: inventory.returnBy
    type: string
    source: inventory

  searchParams:
  
  - name: storeName
    label: inventory.store.name
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?active=true&tenantId=$tenantid|$..code|$..name
    source: store
    isMandatory: true
    wrapper: true

  - name: fromDate
    label: inventory.fromDate
    type: epoch
    source: inventory
    isMandatory: false

  - name: toDate
    label: inventory.toDate
    type: epoch
    source: inventory
    isMandatory: false

  - name: supplierName
    label: inventory.supplierName
    type: singlevaluelist
    source: inventory
    isMandatory: false
  
  - name: materialReturnNo
    label: inventory.materialReturnNo
    type: singlevaluelist
    source: inventory
    isMandatory: false

  - name: materialName
    label: inventory.materialName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  query: select * from material;

# Disposal of Scrap Report
# Need to Change drop down Link based on report and Query
- reportName: disposalOfScrapReport
  summary: Disposal of Scrap Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: storeName
    label: inventory.storeName
    type: string
    source: inventory

  - name: materialCode
    label: inventory.materialCode
    type: string
    source: inventory

  - name: materialName
    label: inventory.materialName
    type: string
    source: inventory

  - name: materialTypeName
    label: inventory.materialTypeName
    type: epoch
    source: inventory

  - name: disposalNo
    label: inventory.disposalNo
    type: string
    source: inventory

  - name: disposalDate
    label: inventory.disposalDate
    type: string
    source: inventory

  - name: disposalQty
    label: inventory.disposalQty
    type: string
    source: inventory

  - name: uom
    label: inventory.uom
    type: string
    source: inventory

  - name: disposalValue
    label: inventory.disposalValue
    type: string
    source: inventory

  - name: lotNo
    label: inventory.lotNo
    type: string
    source: inventory

  - name: disposalBy
    label: inventory.disposalBy
    type: string
    source: inventory

  - name: remarks
    label: inventory.remarks
    type: string
    source: inventory

  searchParams:
  
  - name: storeName
    label: inventory.store.name
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?active=true&tenantId=$tenantid|$..code|$..name
    source: store
    isMandatory: true
    wrapper: true

  - name: disposalFromDate
    label: inventory.disposalFromDate
    type: epoch
    source: inventory
    isMandatory: false

  - name: toDate
    label: inventory.toDate
    type: epoch
    source: inventory
    isMandatory: false

  - name: materialtypename
    label: inventory.materialtypename
    type: singlevaluelist
    source: inventory
    isMandatory: false
  
  - name: disposalNo
    label: inventory.disposalNo
    type: singlevaluelist
    source: inventory
    isMandatory: false

  - name: materialName
    label: inventory.materialName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  query: select * from material;

# Rates comparison with history data Report
# Need to Change drop down Link based on report and Query
- reportName: ratesComparisonWithHistoryDataReport
  summary: Rates comparison with history data Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: materialCode
    label: inventory.materialCode
    type: string
    source: inventory

  - name: materialName
    label: inventory.materialName
    type: string
    source: inventory

  - name: supplierName
    label: inventory.supplierName
    type: string
    source: inventory

  - name: rateType
    label: inventory.rateType
    type: string
    source: inventory

  - name: currentRate
    label: inventory.currentRate
    type: string
    source: inventory

  - name: date
    label: inventory.date
    type: string
    source: inventory

  - name: date
    label: inventory.date
    type: string
    source: inventory

  searchParams:

  - name: supplierName
    label: inventory.supplierName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  - name: materialName
    label: inventory.materialName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  query: select * from material;

# Comparison between different rates Report
# Need to Change drop down Link based on report and Query
- reportName: comparisonBetweenDifferentRatesReport
  summary: Comparison between different rates Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: materialCode
    label: inventory.materialCode
    type: string
    source: inventory

  - name: materialName
    label: inventory.materialName
    type: string
    source: inventory

  - name: supplierName
    label: inventory.supplierName
    type: string
    source: inventory

  - name: DTT
    label: inventory.DTT
    type: string
    source: inventory

  - name: DGSND
    label: inventory.DGSND
    type: string
    source: inventory
    
  - name: tender
    label: inventory.tender
    type: string
    source: inventory

  searchParams:

  - name: supplierName
    label: inventory.supplierName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  - name: materialName
    label: inventory.materialName
    type: singlevaluelist
    source: inventory
    isMandatory: false

  query: select * from material;

# Procurement Expenditure Report
# Need to Change drop down Link based on report and Query
- reportName: procurementExpenditureReport
  summary: Procurement Expenditure Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: budgetHeadCode
    label: inventory.budgetHeadCode
    type: string
    source: inventory

  - name: nameOfBudgetHead
    label: inventory.nameOfBudgetHead
    type: string
    source: inventory

  - name: estimateBudget
    label: inventory.estimateBudget
    type: string
    source: inventory

  - name: actualExpenses
    label: inventory.actualExpenses
    type: string
    source: inventory

  - name: remainingBudget
    label: inventory.remainingBudget
    type: string
    source: inventory
    
  searchParams:

  - name: storeName
    label: inventory.store.name
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?active=true&tenantId=$tenantid|$..code|$..name
    source: inventory
    isMandatory: true
    wrapper: true

  - name: financialYear
    label: inventory.financialYear
    type: singlevaluelist
    pattern: 'list://2017-2018:2017-2018'
    source: inventory
    isMandatory: true

  - name: budgetHead
    label: inventory.budgetHead
    type: singlevaluelist
    source: inventory
    isMandatory: true

  query: select * from material;








