---
ReportDefinitions:
  #  Stock Opening Balance Report
- reportName: openingBalanceReport
  summary: Stock Opening Balance Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:

  - name: financialyear
    label: reports.inventory.openbal.financialyear         
    type: string
    source: materialReceipt

  - name: storeName
    label: reports.inventory.openbal.storeName         
    type: string
    source: materialReceipt

  - name: materialCode
    label: reports.inventory.openbal.MaterialCode         
    type: string
    source: materialReceipt
    
  - name: materialName
    label: reports.inventory.openbal.MaterialName
    type: string
    source: material
    
  - name: materialTypeName
    label: reports.inventory.openbal.MaterialTypeName
    type: string
    source: materialReceiptDetails
    
  - name: uom
    label: reports.inventory.openbal.Uom
    type: string
    source: materialReceiptDetails
  
  - name: qty
    label: reports.inventory.openbal.Qty.
    type: string
    source: materialReceiptDetails
    
  - name: rate
    label: reports.inventory.openbal.Rate
    type: string
    source: materialReceiptDetails
  
  - name: totalAmount
    label: reports.inventory.openbal.TotalAmount
    type: string
    source: materialReceiptDetails
    
  - name: remarks
    label: reports.inventory.openbal.Remarks
    type: string
    source: materialReceiptDetails

  searchParams:
  - name: financialYear
    label: reports.inventory.openbal.financialYear
    type: singlevaluelist
    source: materialReceipt
    isMandatory: true
    
  - name: storeName
    label: reports.inventory.openbal.storeName
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?tenantId=$tenantId|$..code|$..name 
    source: store
    isMandatory: true
    
  - name: materialTypeName
    label: reports.inventory.openbal.materialTypeName
    type: string
    source: materialReceipt 
    isMandatory: false
    searchClause: AND matrcpt.receiptType = $materialTypeName
    
  - name: materialName
    label: reports.inventory.openbal.materialName
    type: string
    source: materialReceipt  
    isMandatory: false
    searchClause: AND mat.name = $materialName
  query:  SELECT matrcpt.financialyear as financialyear,
                  matrcpt.receivingstore as storeName,
                  matrcptdtl.material as materialcode,
                  matrcpt.receiptType as materialtypename,
                  matrcptdtl.uomno as uom,
                  matrcptdtl.receivedqty as qty,
                  matrcptdtl.unitrate as rate,
                  (matrcptdtl.unitrate * matrcptdtl.receivedqty) as totalamount,
                  matrcptdtl.remarks as remarks
          FROM materialreceipt matrcpt,
               materialreceiptdetail matrcptdtl
          WHERE matrcpt.financialyear = $financialyear
                      AND matrcpt.receivingstore = $storeName
                      AND matrcpt.receipttype ='OPENING BALANCE'
                      AND matrcpt.tenantid= $tenantId
                      AND matrcpt.tenantid=matrcptdtl.tenantid
                      AND matrcpt.mrnnumber = matrcptdtl.mrnnumber

