---
ReportDefinitions:
  #  Stock Opening Balance Report
- reportName: openingbalance
  summary: Stock Opening Balance Report
  version: 1.0.0
  moduleName: inventory
  sourceColumns:
  - name: materialCode
    label: reports.inventory.openbal.MaterialCode         
    type: string
    source: material
    
  - name: materialName
    label: reports.inventory.openbal.MaterialName
    type: string
    source: material
    
  - name: materialTypeName
    label: reports.inventory.openbal.MaterialTypeName
    type: string
    source: materialReceiptDetails
    
  - name: uom
    label: reports.inventory.openbal.Uom
    type: string
    source: materialReceiptDetails
  
  - name: qty
    label: reports.inventory.openbal.Qty.
    type: string
    source: materialReceiptDetails
    
  - name: rate
    label: reports.inventory.openbal.Rate
    type: string
    source: materialReceiptDetails
  
  - name: totalAmount
    label: reports.inventory.openbal.TotalAmount
    type: string
    source: materialReceiptDetails
    
  - name: remarks
    label: reports.inventory.openbal.Remarks
    type: string
    source: materialReceiptDetails
    
      
  searchParams:
  - name: financialYear
    label: reports.inventory.openbal.financialYear
    type: String
    source: materialReceipt
    isMandatory: true
    
  - name: storeName
    label: reports.inventory.openbal.storeName
    type: singlevaluelist
    pattern: http://inventory-services:8080/inventory-services/stores/_search?tenantId=$tenantId|$..code|$..name 
    source: store
    isMandatory: true
    
  - name: materialTypeName
    label: reports.inventory.openbal.materialTypeName
    type: string
    source: materialReceipt 
    isMandatory: false
    searchClause: AND matrcpt.receiptType = $materialTypeName
    
  - name: materialName
    label: reports.inventory.openbal.materialName
    type: singlevaluelist
    source: materialReceipt  
    isMandatory: false
    searchClause: AND mat.name = $materialName
  query:  SELECT matrcptdtl.material as materialcode,
                mat.name as materialName,
                matrcpt.receiptType as materialTypeName,
                matrcptdtl.receivedqty as qty,
                matrcptdtl.unitrate as rate,
                (matrcptdtl.receivedqty * matrcptdtl.unitrate) as totalamount,
                matrcptdtl.remarks as remarks
          FROM materialreceiptdetail  matrcptdtl ,
                materialreceipt matrcpt,
                material mat
          WHERE matrcpt.financialYear = $financialYear
                AND matrcpt.receivingStore = $storeName
                AND matrcptdtl.tenantid = $tenantId
                AND matrcpt.tenantid = matrcptdtl.tenantId
                AND matrcpt.mrnnumber = matrcptdtl.mrnnumber
                AND mat.tenantId = matrcptdtl.tanantId
                AND mat.tenantId = matrcpt.tenantId
    
    
