serviceMaps:
 serviceName: Works Quality Testing
 mappings:
 - version: 1.0
   name: Quality Testing create and update
   description: Persists Quality Testing in egw_qualitycontrol table
   fromTopic: works-qualitytesting-createandupdate
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_qualitytesting(id, tenantid, letterOfAcceptanceEstimate, remarks, status, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET remarks=EXCLUDED.remarks, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted= EXCLUDED.deleted;
      basePath: $.qualityTestings.*
      jsonMaps:

       - jsonPath: $.qualityTestings.*.id

       - jsonPath: $.qualityTestings.*.tenantId

       - jsonPath: $.qualityTestings.*.letterOfAcceptanceEstimate.id

       - jsonPath: $.qualityTestings.*.remarks
       
       - jsonPath: $.qualityTestings.*.status.code

       - jsonPath: $.qualityTestings.*.auditDetails.createdBy

       - jsonPath: $.qualityTestings.*.auditDetails.createdTime

       - jsonPath: $.qualityTestings.*.auditDetails.lastModifiedBy

       - jsonPath: $.qualityTestings.*.auditDetails.lastModifiedTime

       - jsonPath: $.qualityTestings.*.deleted
         type: BOOLEAN

    - query: INSERT INTO egw_qualitytesting_details(id, tenantid, qualityTesting, materialName, testName, resultUnit, minimumValue, maximumValue, hodRemarks, coRemarks, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id,tenantid) DO UPDATE SET materialName=EXCLUDED.materialName, testName=EXCLUDED.testName, resultUnit=EXCLUDED.resultUnit, minimumValue=EXCLUDED.minimumValue , maximumValue=EXCLUDED.maximumValue, hodRemarks=EXCLUDED.hodRemarks, coRemarks=EXCLUDED.coRemarks, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted= EXCLUDED.deleted;
      basePath: $.qualityTestings.*.qualityTestingDetails.*
      jsonMaps:

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.id

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.tenantId

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.qualityTesting

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.materialName

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.testName

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.resultUnit
       
       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.minimumValue
       
       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.maximumValue
       
       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.hodRemarks
       
       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.coRemarks

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.auditDetails.createdBy

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.auditDetails.createdTime

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.auditDetails.lastModifiedTime

       - jsonPath: $.qualityTestings.*.qualityTestingDetails.*.deleted
         type: BOOLEAN

    - query: INSERT INTO egw_documentdetail(id, tenantid, objectid, objecttype, documenttype, filestore, latitude, longitude, description, dateofcapture, workprogress, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET filestore=EXCLUDED.filestore, documenttype= EXCLUDED.documenttype, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, description=EXCLUDED.description, dateofcapture=EXCLUDED.dateofcapture, workprogress=EXCLUDED.workprogress, lastmodifiedtime=EXCLUDED.lastmodifiedtime, lastmodifiedby=EXCLUDED.lastmodifiedby, deleted= EXCLUDED.deleted;

      basePath: $.qualityTestings.*.testReports.*
      jsonMaps:

        - jsonPath: $.qualityTestings.*.testReports.*.id

        - jsonPath: $.qualityTestings.*.testReports.*.tenantId

        - jsonPath: $.qualityTestings.*.testReports.*.objectId

        - jsonPath: $.qualityTestings.*.testReports.*.objectType

        - jsonPath: $.qualityTestings.*.testReports.*.documentType

        - jsonPath: $.qualityTestings.*.testReports.*.fileStore

        - jsonPath: $.qualityTestings.*.testReports.*.latitude

        - jsonPath: $.qualityTestings.*.testReports.*.longitude

        - jsonPath: $.qualityTestings.*.testReports.*.description

        - jsonPath: $.qualityTestings.*.testReports.*.dateOfCapture

        - jsonPath: $.qualityTestings.*.testReports.*.workProgress

        - jsonPath: $.qualityTestings.*.testReports.*.auditDetails.createdBy

        - jsonPath: $.qualityTestings.*.testReports.*.auditDetails.createdTime

        - jsonPath: $.qualityTestings.*.testReports.*.auditDetails.lastModifiedBy

        - jsonPath: $.qualityTestings.*.testReports.*.auditDetails.lastModifiedTime

        - jsonPath: $.qualityTestings.*.testReports.*.deleted
          type: BOOLEAN

