serviceMaps:
 serviceName: Works Estimate
 mappings:
 - version: 1.0
   name: AbstractEstimate Create
   description: Persists abstract estimate  in egw_abstractestimate table
   fromTopic: works-abstract-estimate-create
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_abstractestimate(
        id, tenantid, abstractestimatenumber, subject, fund, referencetype, 
        referencenumber, function, description, budgethead, scheme, subscheme, 
        dateofproposal, department, adminsanctionnumber, adminsanctiondate, 
        adminsanctionby, status, beneficiary, modeofallotment, typeofwork, 
        natureofwork, subtypeofwork, ward, technicalsanctionnumber, technicalsanctiondate, 
        technicalsanctionby, locality, workcategory, councilresolutionnumber, 
        councilresolutiondate, workordercreated, billscreated, spilloverflag, 
        cancellationreason, cancellationremarks, detailedestimatecreated, 
        stateid, Asset, implementationperiod, fundavailable, fundsanctioningauthority, 
        pmcrequired, pmctype, pmcname, createdby, createdtime, lastmodifiedby, 
        lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, 
        ?, ?, ?, ?, 
        ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, 
        ?);
      basePath: $.abstractEstimates.*
      jsonMaps:
         
       - jsonPath: $.abstractEstimates.*.id
       
       - jsonPath: $.abstractEstimates.*.tenantId
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateNumber
         
       - jsonPath: $.abstractEstimates.*.subject
       
       - jsonPath: $.abstractEstimates.*.fund
       
       - jsonPath: $.abstractEstimates.*.referenceType
       
       - jsonPath: $.abstractEstimates.*.referenceNumber
       
       - jsonPath: $.abstractEstimates.*.function
       
       - jsonPath: $.abstractEstimates.*.description
       
       - jsonPath: $.abstractEstimates.*.budgetHead
       
       - jsonPath: $.abstractEstimates.*.scheme
                 
       - jsonPath: $.abstractEstimates.*.subScheme
                 
       - jsonPath: $.abstractEstimates.*.dateOfProposal
         dbType: LONG
         
       - jsonPath: $.abstractEstimates.*.department
                  
       - jsonPath: $.abstractEstimates.*.adminSanctionNumber
       
       - jsonPath: $.abstractEstimates.*.adminSanctionDate
         dbType: LONG
       
       - jsonPath: $.abstractEstimates.*.adminSanctionBy
       
       - jsonPath: $.abstractEstimates.*.status
       
       - jsonPath: $.abstractEstimates.*.beneficiary
                  
       - jsonPath: $.abstractEstimates.*.modeOfAllotment.code
         
       - jsonPath: $.abstractEstimates.*.typeOfWork.code
       
       - jsonPath: $.abstractEstimates.*.natureOfWork.code
       
       - jsonPath: $.abstractEstimates.*.subTypeOfWork.code
       
       - jsonPath: $.abstractEstimates.*.ward.code
       
       - jsonPath: $.abstractEstimates.*.technicalSanctionNumber
               
       - jsonPath: $.abstractEstimates.*.technicalSanctionDate
         dbType: LONG
       
       - jsonPath: $.abstractEstimates.*.technicalSanctionBy
       
       - jsonPath: $.abstractEstimates.*.locality.code
       
       - jsonPath: $.abstractEstimates.*.workCategory
       
       - jsonPath: $.abstractEstimates.*.councilResolutionNumber
                
       - jsonPath: $.abstractEstimates.*.councilResolutionDate
                
       - jsonPath: $.abstractEstimates.*.workOrderCreated
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.billsCreated
         type: BOOLEAN
                  
       - jsonPath: $.abstractEstimates.*.spillOverFlag
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.cancellationReason
       
       - jsonPath: $.abstractEstimates.*.cancellationRemarks
       
       - jsonPath: $.abstractEstimates.*.detailedEstimateCreated
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.stateId
       
       - jsonPath: $.abstractEstimates.*.asset
       
       - jsonPath: $.abstractEstimates.*.implementationPeriod
         dbType: LONG
                
       - jsonPath: $.abstractEstimates.*.fundAvailable
         type: BOOLEAN
                  
       - jsonPath: $.abstractEstimates.*.fundSanctioningAuthority
                  
       - jsonPath: $.abstractEstimates.*.pmcRequired
         type: BOOLEAN
                
       - jsonPath: $.abstractEstimates.*.pmcType
               
       - jsonPath: $.abstractEstimates.*.pmcName
       
       - jsonPath: $.abstractEstimates.*.auditDetails.createdBy
 
       - jsonPath: $.abstractEstimates.*.auditDetails.createdTime
       
       - jsonPath: $.abstractEstimates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.abstractEstimates.*.auditDetails.lastModifiedTime 
       
    - query: INSERT INTO egw_abstractestimate_details(
            id, tenantid, abstractestimate, nameofwork, estimateamount, estimatenumber, 
            createdby, createdtime, lastmodifiedby, lastmodifiedtime, grossamountbilled, 
            projectcode) VALUES 
            (?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?);
      basePath: $.abstractEstimates.*.abstractEstimateDetails.*
      jsonMaps:
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.id
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.tenantId
         
       - jsonPath: $.abstractEstimates[?({id} in @.abstractEstimateDetails[*].id)].id
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.nameOfWork
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.estimateAmount
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.estimateNumber
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.createdBy
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.createdTime

       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.lastModifiedTime

       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.grossAmountBilled
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectcode

 - version: 1.0
   name: Project Code
   description: Persists Project Code in egw_projectcode table
   fromTopic: works-projectcode-create
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_projectcode(
            id, tenantid, code, active, description, name, status , 
            completiondate, projectvalue, createdby, createdtime, lastmodifiedby, 
            lastmodifiedtime) VALUES 
            (?, ?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?);
      basePath: $.projectCodes.*
      jsonMaps:
         
       - jsonPath: $.projectCodes.*.id
         
       - jsonPath: $.projectCodes.*.tenantId
         
       - jsonPath: $.projectCodes.*.code
       
       - jsonPath: $.projectCodes.*.active
       
       - jsonPath: $.projectCodes.*.description
       
       - jsonPath: $.projectCodes.*.name
       
       - jsonPath: $.projectCodes.*.status
       
       - jsonPath: $.projectCodes.*.completionDate
        
       - jsonPath: $.projectCodes.*.projectValue
       
       - jsonPath: $.projectCodes.*.auditDetails.createdBy
         dbType: LONG
 
       - jsonPath: $.projectCodes.*.auditDetails.createdTime
       
       - jsonPath: $.projectCodes.*.auditDetails.lastModifiedBy
         dbType: LONG

       - jsonPath: $.projectCodes.*.auditDetails.lastModifiedTime

 - version: 1.0
   name: Works Project Code Update
   description: Update Project Code in egw_projectcode table
   fromTopic: works-projectcode-update
   isTransaction: true
   queryMaps:   
    - query: UPDATE egw_projectcode SET status= ?, active=?, projectValue=?, completionDate=?, lastModifiedBy=?, lastModifiedTime=?  WHERE id = ? AND tenantId = ?;
      basePath: $.projectCodes.*
      jsonMaps:
         
       - jsonPath: $.projectCodes.*.status

       - jsonPath: $.projectCodes.*.active

       - jsonPath: $.projectCodes.*.projectValue

       - jsonPath: $.projectCodes.*.completionDate

       - jsonPath: $.projectCodes.*.auditDetails.lastModifiedBy
         dbType: LONG
       
       - jsonPath: $.projectCodes.*.auditDetails.lastModifiedTime

       - jsonPath: $.projectCodes.*.id
       
       - jsonPath: $.projectCodes.*.tenantId
       
 - version: 1.0
   name: Detailed AbstractEstimate Create
   description: Persists detailed abstract estimate  in egw_detailed_estimate table
   fromTopic: works-detailed-abstract-estimate-create #need to change. It's a temp name
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_detailed_estimate(
            id, tenantid, estimatenumber, estimatedate, nameofwork, description, 
            department, adminsanctionnumber, adminsanctiondate, adminsanctionby, 
            status, workvalue, estimatevalue, projectcode, parent, copiedfrom, 
            approveddate, approvedby, copiedestimate, beneficiary, modeofallotment, 
            workstype, workssubtype, natureofwork, ward, location, longitude, 
            latitude, workcategory, locality, councilresolutionnumber, councilresolutiondate, 
            workordercreated, billscreated, spilloverflag, grossamountbilled, 
            cancellationreason, cancellationremarks, totalincludingre, abstractestimatedetail, 
            stateid, fund, function, functionary, scheme, subscheme, budgetgroup, 
            createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
            VALUES (?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, 
            ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?);
      basePath: $.detailedEstimates.*
      jsonMaps:
         
       - jsonPath: $.detailedEstimates.*.id
       
       - jsonPath: $.detailedEstimates.*.tenantId
         
       - jsonPath: $.detailedEstimates.*.estimateNumber
         
       - jsonPath: $.detailedEstimates.*.nameOfWork
       
       - jsonPath: $.detailedEstimates.*.description
       
       - jsonPath: $.detailedEstimates.*.department
       
       - jsonPath: $.detailedEstimates.*.adminSanctionNumber
       
       - jsonPath: $.detailedEstimates.*.adminSanctionDate
         dbType: LONG
       
       - jsonPath: $.detailedEstimates.*.adminSanctionBy
       
       - jsonPath: $.detailedEstimates.*.status
       
       - jsonPath: $.detailedEstimates.*.workValue
                 
       - jsonPath: $.detailedEstimates.*.estimateValue
                 
       - jsonPath: $.detailedEstimates.*.projectCode
         
       - jsonPath: $.detailedEstimates.*.parent
                  
       - jsonPath: $.detailedEstimates.*.copiedFrom
       
       - jsonPath: $.detailedEstimates.*.approvedDate
         dbType: LONG
       
       - jsonPath: $.detailedEstimates.*.approvedBy
       
       - jsonPath: $.detailedEstimates.*.copiedEstimate
         type: BOOLEAN
       
       - jsonPath: $.detailedEstimates.*.beneficiary
                  
       - jsonPath: $.detailedEstimates.*.modeOfAllotment.code
         
       - jsonPath: $.detailedEstimates.*.worksType.code
       
       - jsonPath: $.detailedEstimates.*.worksSubtype.code
       
       - jsonPath: $.detailedEstimates.*.subTypeOfWork.code
       
       - jsonPath: $.detailedEstimates.*.natureOfWork.code
       
       - jsonPath: $.detailedEstimates.*.ward.code
       
       - jsonPath: $.detailedEstimates.*.location.code
       
       - jsonPath: $.detailedEstimates.*.longitude
       
       - jsonPath: $.detailedEstimates.*.latitude
       
       - jsonPath: $.detailedEstimates.*.workCategory
       
       - jsonPath: $.detailedEstimates.*.locality.code
       
       - jsonPath: $.detailedEstimates.*.councilResolutionNumber
                
       - jsonPath: $.detailedEstimates.*.councilResolutionDate
         dbType: LONG
                
       - jsonPath: $.detailedEstimates.*.workOrderCreated
         type: BOOLEAN
       
       - jsonPath: $.detailedEstimates.*.billsCreated
         type: BOOLEAN
                  
       - jsonPath: $.detailedEstimates.*.spillOverFlag
         type: BOOLEAN

       - jsonPath: $.detailedEstimates.*.grossAmountBilled
       
       - jsonPath: $.detailedEstimates.*.cancellationReason
       
       - jsonPath: $.detailedEstimates.*.cancellationRemarks
       
       - jsonPath: $.detailedEstimates.*.totalIncludingRE
       
       - jsonPath: $.detailedEstimates.*.abstractEstimateDetail

       - jsonPath: $.detailedEstimates.*.stateId

       - jsonPath: $.detailedEstimates.*.fund

       - jsonPath: $.detailedEstimates.*.function

       - jsonPath: $.detailedEstimates.*.functionary

       - jsonPath: $.detailedEstimates.*.scheme

       - jsonPath: $.detailedEstimates.*.subScheme

       - jsonPath: $.detailedEstimates.*.budgetGroup
       
       - jsonPath: $.detailedEstimates.*.auditDetails.createdBy
 
       - jsonPath: $.detailedEstimates.*.auditDetails.createdTime
       
       - jsonPath: $.detailedEstimates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.detailedEstimates.*.auditDetails.lastModifiedTime
