serviceMaps:
 serviceName: Works Masters
 mappings:
 - version: 1.0
   name: ScheduleOfRate Create
   description: Persists Schedule Of Rate in egw_scheduleofrate table
   fromTopic: works-sorrate-create-validated
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_scheduleofrate(id, tenantid, code, description, schedulecategory, uom, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.id
       
       - jsonPath: $.scheduleOfRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates.*.code
         
       - jsonPath: $.scheduleOfRates.*.description
       
       - jsonPath: $.scheduleOfRates.*.scheduleCategory.code
       
       - jsonPath: $.scheduleOfRates.*.uom.code
       
       - jsonPath: $.scheduleOfRates.*.auditDetails.createdBy
 
       - jsonPath: $.scheduleOfRates.*.auditDetails.createdTime
       
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime
       
    - query: INSERT INTO egw_sorrate(id, tenantid, scheduleofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.sorRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.sorRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedTime

    - query: INSERT INTO egw_marketrate(id, tenantid, scheduleofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.marketRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.marketRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedTime

 - version: 1.0
   name: ScheduleOfRate Update
   description: Persists Schedule Of Rate in egw_scheduleofrate table
   fromTopic: works-sorrate-update-validated
   isTransaction: true
   queryMaps:
    - query: update egw_scheduleofrate set code=?, description=?, schedulecategory=?, uom=?, lastmodifiedby=?, lastmodifiedtime=? WHERE id=? AND tenantid=?;
      basePath: $.scheduleOfRates.*
      jsonMaps:

       - jsonPath: $.scheduleOfRates.*.code

       - jsonPath: $.scheduleOfRates.*.description

       - jsonPath: $.scheduleOfRates.*.scheduleCategory.code

       - jsonPath: $.scheduleOfRates.*.uom.code

       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedBy

       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime

       - jsonPath: $.scheduleOfRates.*.id

       - jsonPath: $.scheduleOfRates.*.tenantId

    - query: update egw_sorrate set fromdate=?, todate=?, rate=?, lastmodifiedby=?, lastmodifiedtime=? where scheduleofrate=? and id=? and tenantid=?;
      basePath: $.scheduleOfRates.*.sorRates.*
      jsonMaps:

       - jsonPath: $.scheduleOfRates.*.sorRates.*.fromDate

       - jsonPath: $.scheduleOfRates.*.sorRates.*.toDate

       - jsonPath: $.scheduleOfRates.*.sorRates.*.rate

       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedBy

       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedTime

       - jsonPath: $.scheduleOfRates.*.id

       - jsonPath: $.scheduleOfRates.*.sorRates.*.id

       - jsonPath: $.scheduleOfRates.*.sorRates.*.tenantId

    - query: update egw_marketrate set fromdate=?, todate=?, rate=?, lastmodifiedby=?, lastmodifiedtime=? where scheduleofrate=? and id=? and tenantid=?;
      basePath: $.scheduleOfRates.*.marketRates.*
      jsonMaps:

       - jsonPath: $.scheduleOfRates.*.marketRates.*.fromDate

       - jsonPath: $.scheduleOfRates.*.marketRates.*.toDate

       - jsonPath: $.scheduleOfRates.*.marketRates.*.rate

       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedBy

       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedTime

       - jsonPath: $.scheduleOfRates.*.id

       - jsonPath: $.scheduleOfRates.*.marketRates.*.id

       - jsonPath: $.scheduleOfRates.*.marketRates.*.tenantId

 - version: 1.0
   name: Contractor Create
   description: Persists Contractor in egw_contractor table
   fromTopic: works-contractor-create
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_contractor(id, tenantid, name, code, correspondenceaddress, paymentaddress, contactperson, email, narration, mobilenumber, pannumber, tinnumber, bank, bankaccountnumber, pwdapprovalcode, exemptedfrom, pwdapprovalvalidtill, epfregistrationnumber, accountcode, ifsccode, contractorclass, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.contractors.*
      jsonMaps:
         
       - jsonPath: $.contractors.*.id
       
       - jsonPath: $.contractors.*.tenantId
       
       - jsonPath: $.contractors.*.name
         
       - jsonPath: $.contractors.*.code
         
       - jsonPath: $.contractors.*.correspondenceAddress
       
       - jsonPath: $.contractors.*.paymentAddress
       
       - jsonPath: $.contractors.*.contactPerson
       
       - jsonPath: $.contractors.*.email
       
       - jsonPath: $.contractors.*.narration
       
       - jsonPath: $.contractors.*.mobileNumber
       
       - jsonPath: $.contractors.*.panNumber
       
       - jsonPath: $.contractors.*.tinNumber
       
       - jsonPath: $.contractors.*.bank.code
       
       - jsonPath: $.contractors.*.bankAccountNumber
       
       - jsonPath: $.contractors.*.pwdApprovalCode
       
       - jsonPath: $.contractors.*.exemptedFrom
       
       - jsonPath: $.contractors.*.pwdApprovalValidTill
         dbType: LONG
       
       - jsonPath: $.contractors.*.epfRegistrationNumber
       
       - jsonPath: $.contractors.*.accountCode
       
       - jsonPath: $.contractors.*.ifscCode
       
       - jsonPath: $.contractors.*.contractorClass
       
       - jsonPath: $.contractors.*.auditDetails.createdBy
 
       - jsonPath: $.contractors.*.auditDetails.createdTime
       
       - jsonPath: $.contractors.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime 
       
 - version: 1.0
   name: Contractor Update
   description: Update Contractor in egw_contractor table
   fromTopic: works-contractor-update
   isTransaction: true
   queryMaps:
    - query: UPDATE egw_contractor SET name=?, code=?, correspondenceaddress=?, paymentaddress=?, contactperson=?, email=?, narration=?, mobilenumber=?, pannumber=?, tinnumber=?, bank=?, bankaccountnumber=?, pwdapprovalcode=?, exemptedfrom=?, pwdapprovalvalidtill=?, epfregistrationnumber=?, accountcode=?, ifsccode=?, contractorclass=?, lastmodifiedby=?, lastmodifiedtime=? WHERE id=? AND tenantid=?;
      basePath: $.contractors.*
      jsonMaps:
         
       - jsonPath: $.contractors.*.name
         
       - jsonPath: $.contractors.*.code
         
       - jsonPath: $.contractors.*.correspondenceAddress
       
       - jsonPath: $.contractors.*.paymentAddress
       
       - jsonPath: $.contractors.*.contactPerson
       
       - jsonPath: $.contractors.*.email
       
       - jsonPath: $.contractors.*.narration
       
       - jsonPath: $.contractors.*.mobileNumber
       
       - jsonPath: $.contractors.*.panNumber
       
       - jsonPath: $.contractors.*.tinNumber
       
       - jsonPath: $.contractors.*.bank.code
       
       - jsonPath: $.contractors.*.bankAccountNumber
       
       - jsonPath: $.contractors.*.pwdApprovalCode
       
       - jsonPath: $.contractors.*.exemptedFrom
       
       - jsonPath: $.contractors.*.pwdApprovalValidTill
         dbType: LONG
       
       - jsonPath: $.contractors.*.epfRegistrationNumber
       
       - jsonPath: $.contractors.*.accountCode
       
       - jsonPath: $.contractors.*.ifscCode
       
       - jsonPath: $.contractors.*.contractorClass
       
       - jsonPath: $.contractors.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime
       
       - jsonPath: $.contractors.*.id
       
       - jsonPath: $.contractors.*.tenantId

