serviceMaps:
 serviceName: Works Estimate
 mappings:
 - version: 1.0
   name: AbstractEstimate Create
   description: Persists abstract estimate  in egw_abstractestimate table
   fromTopic: works-abstract-estimate-create
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_abstractestimate(
        id, tenantid, abstractestimatenumber, subject, fund, referencetype, 
        referencenumber, function, description, budgethead, scheme, subscheme, 
        dateofproposal, department, adminsanctionnumber, adminsanctiondate, 
        adminsanctionby, status, beneficiary, modeofallotment, typeofwork, 
        natureofwork, subtypeofwork, ward, technicalsanctionnumber, technicalsanctiondate, 
        technicalsanctionby, locality, workcategory, councilresolutionnumber, 
        councilresolutiondate, workordercreated, billscreated, spilloverflag, 
        cancellationreason, cancellationremarks, detailedestimatecreated, 
        stateid, Asset, implementationperiod, fundavailable, fundsanctioningauthority, 
        pmcrequired, pmctype, pmcname, createdby, createdtime, lastmodifiedby, 
        lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, 
        ?, ?, ?, ?, 
        ?, ?, ?, 
        ?, ?, ?, ?, ?, 
        ?, ?, ?, ?, ?, ?, 
        ?);
      basePath: $.abstractEstimates.*
      jsonMaps:
         
       - jsonPath: $.abstractEstimates.*.id
       
       - jsonPath: $.abstractEstimates.*.tenantId
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateNumber
         
       - jsonPath: $.abstractEstimates.*.subject
       
       - jsonPath: $.abstractEstimates.*.fund
       
       - jsonPath: $.abstractEstimates.*.referenceType
       
       - jsonPath: $.abstractEstimates.*.referenceNumber
       
       - jsonPath: $.abstractEstimates.*.function
       
       - jsonPath: $.abstractEstimates.*.description
       
       - jsonPath: $.abstractEstimates.*.budgetHead
       
       - jsonPath: $.abstractEstimates.*.scheme
                 
       - jsonPath: $.abstractEstimates.*.subScheme
                 
       - jsonPath: $.abstractEstimates.*.dateOfProposal
         dbType: LONG
         
       - jsonPath: $.abstractEstimates.*.department
                  
       - jsonPath: $.abstractEstimates.*.adminSanctionNumber
       
       - jsonPath: $.abstractEstimates.*.adminSanctionDate
         dbType: LONG
       
       - jsonPath: $.abstractEstimates.*.adminSanctionBy
       
       - jsonPath: $.abstractEstimates.*.status
       
       - jsonPath: $.abstractEstimates.*.beneficiary
                  
       - jsonPath: $.abstractEstimates.*.modeOfAllotment.code
         
       - jsonPath: $.abstractEstimates.*.typeOfWork.code
       
       - jsonPath: $.abstractEstimates.*.natureOfWork.code
       
       - jsonPath: $.abstractEstimates.*.subTypeOfWork.code
       
       - jsonPath: $.abstractEstimates.*.ward.code
       
       - jsonPath: $.abstractEstimates.*.technicalSanctionNumber
               
       - jsonPath: $.abstractEstimates.*.technicalSanctionDate
         dbType: LONG
       
       - jsonPath: $.abstractEstimates.*.technicalSanctionBy
       
       - jsonPath: $.abstractEstimates.*.locality.code
       
       - jsonPath: $.abstractEstimates.*.workCategory
       
       - jsonPath: $.abstractEstimates.*.councilResolutionNumber
                
       - jsonPath: $.abstractEstimates.*.councilResolutionDate
                
       - jsonPath: $.abstractEstimates.*.workOrderCreated
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.billsCreated
         type: BOOLEAN
                  
       - jsonPath: $.abstractEstimates.*.spillOverFlag
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.cancellationReason
       
       - jsonPath: $.abstractEstimates.*.cancellationRemarks
       
       - jsonPath: $.abstractEstimates.*.detailedEstimateCreated
         type: BOOLEAN
       
       - jsonPath: $.abstractEstimates.*.stateId
       
       - jsonPath: $.abstractEstimates.*.asset
       
       - jsonPath: $.abstractEstimates.*.implementationPeriod
         dbType: LONG
                
       - jsonPath: $.abstractEstimates.*.fundAvailable
         type: BOOLEAN
                  
       - jsonPath: $.abstractEstimates.*.fundSanctioningAuthority
                  
       - jsonPath: $.abstractEstimates.*.pmcRequired
         type: BOOLEAN
                
       - jsonPath: $.abstractEstimates.*.pmcType
               
       - jsonPath: $.abstractEstimates.*.pmcName
       
       - jsonPath: $.abstractEstimates.*.auditDetails.createdBy
 
       - jsonPath: $.AbstractEstimate.*.auditDetails.createdTime
       
       - jsonPath: $.abstractEstimates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.AbstractEstimate.*.auditDetails.lastModifiedTime 
       
    - query: INSERT INTO egw_abstractestimate_details(
            id, tenantid, abstractestimate, nameofwork, estimateamount, estimatenumber, 
            createdby, createdtime, lastmodifiedby, lastmodifiedtime, grossamountbilled, 
            projectcode) VALUES 
            (?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?);
      basePath: $.abstractEstimates.*.abstractEstimateDetails.*
      jsonMaps:
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.id
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.tenantId
         
       - jsonPath: $.abstractEstimates[?({id} in @.abstractEstimateDetails[*].id)].id
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.nameOfWork
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.estimateAmount
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.estimateNumber
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.createdBy
       
       - jsonPath: $.AbstractEstimate.*.abstractEstimateDetails.*.auditDetails.createdTime

       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.AbstractEstimate.*.abstractEstimateDetails.*.auditDetails.lastModifiedTime

       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.grossAmountBilled
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectcode
       
       
    - query: INSERT INTO egw_projectcode(
            id, tenantid, code, detailedestimate, description, name, status, 
            completiondate, projectvalue, createdby, createdtime, lastmodifiedby, 
            lastmodifiedtime) VALUES 
            (?, ?, ?, ?, ?, ?, ?, 
            ?, ?, ?, ?, ?, 
            ?);
      basePath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*
      jsonMaps:
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.id
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.tenantId
         
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.code
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.detailedEstimate
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.description
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.name
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.status
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.completionDate
        
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.projectValue
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.auditDetails.createdBy
 
       - jsonPath: $.AbstractEstimate.*.abstractEstimateDetails.*.projectCode.*.auditDetails.createdTime
       
       - jsonPath: $.abstractEstimates.*.abstractEstimateDetails.*.projectCode.*.auditDetails.lastModifiedBy

       - jsonPath: $.AbstractEstimate.*.abstractEstimateDetails.*.projectCode.*.auditDetails.lastModifiedTime

