serviceMaps:
 serviceName: Works Masters
 mappings:
 - version: 1.0
   name: ScheduleOfRate Create
   description: Persists Schedule Of Rate in egw_scheduleofrate table
   fromTopic: works-sorrate-create-validated
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_scheduleofrate(id, tenantid, code, description, schedulecategory, uom, createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.id
       
       - jsonPath: $.scheduleOfRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates.*.code
         
       - jsonPath: $.scheduleOfRates.*.description
       
       - jsonPath: $.scheduleOfRates.*.scheduleCategory.code
       
       - jsonPath: $.scheduleOfRates.*.uom.code
       
       - jsonPath: $.scheduleOfRates.*.auditDetails.createdBy
 
       - jsonPath: $.scheduleOfRates.*.auditDetails.createdTime
       
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime 
       
    - query: INSERT INTO egw_sorrate(id, tenantid, schedulerofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
		VALUES(?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.sorRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.sorRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedTime

    - query: INSERT INTO egw_marketrate(id, tenantid, schedulerofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
		VALUES(?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.marketRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.marketRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedTime

 - version: 1.0
   name: ScheduleOfRate Create
   description: Persists Schedule Of Rate in egw_scheduleofrate table
   fromTopic: works-sorrate-update-validated
   isTransaction: true
   queryMaps:
    - query: update egw_scheduleofrate set code=?, description=?, schedulecategory=?, uom=?, lastmodifiedby=?, lastmodifiedtime=? WHERE id=? AND tenantid=?;
      basePath: $.scheduleOfRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.code
         
       - jsonPath: $.scheduleOfRates.*.description
       
       - jsonPath: $.scheduleOfRates.*.scheduleCategory.code
       
       - jsonPath: $.scheduleOfRates.*.uom.code
       
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.scheduleOfRates.*.auditDetails.lastModifiedTime

       - jsonPath: $.scheduleOfRates.*.id
       
       - jsonPath: $.scheduleOfRates.*.tenantId
       
    - query: INSERT INTO egw_sorrate(id, tenantid, schedulerofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
		VALUES(?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.sorRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.sorRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.sorRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.sorRates.*.auditDetails.lastModifiedTime

    - query: INSERT INTO egw_marketrate(id, tenantid, schedulerofrate, fromdate, todate, rate,  createdby, createdtime, lastmodifiedby, lastmodifiedtime) 
		VALUES(?, ?, ?, ?, ?, ?);
      basePath: $.scheduleOfRates.*.marketRates.*
      jsonMaps:
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.id
         
       - jsonPath: $.scheduleOfRates.*.marketRates.*.tenantId
         
       - jsonPath: $.scheduleOfRates[?({id} in @.marketRates[*].id)].id
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.fromDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.toDate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.rate
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.createdTime

       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.scheduleOfRates.*.marketRates.*.auditDetails.lastModifiedTime

