version: '2'
services:
  zookeeper:
    image: egovio/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: egovio/kafka:latest
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "ap.public.mseva.locationassigned:1:1,ap.public.mseva.assigned:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  employeeassignment:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    links:
      - kafka
