version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    image: egovio/frontend:latest
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MASTER_SERVER=true
      - CORS_ENABLED=true
    ports:
      - "3000:8080"

  pgrspringboot:
    image: springboot:latest
    ports:
      - "8080:8080"
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - GENERATE_DDL=false
