version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass

  pgrspringboot:
    image: springboot:latest
    ports:
      - "8080:8080"
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypass
