version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "ap.public.mseva.validated:1:1,ap.public.mseva.assigned:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    image: egovio/frontend:latest
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MASTER_SERVER=true
      - CORS_ENABLED=true
    ports:
      - "3000:8080"

  pgrspringboot:
    image: springboot:latest
    ports:
      - "8080:8080"
    links:
      - postgres:pghost
      - kafka
    environment:
      - DB_HOST=pghost
      - DB_NAME=mydb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - GENERATE_DDL=false
