reportName: GrievanceByType
summary: Report grouped by Grievance Type and status - based on a date period
version: 1.0.0
sourceColumns:
      - name: id 
        label: reports.pgr.complainttype.name
        type: string
        source: egpgr_complainttype 
      - name: consumercode
        label: reports.pgr.seva.status
        type: string
        source: seva 
      - name: consumertype
        label: reports.pgr.withinsla
        type: number
        source: seva 
      - name: businessservice
        label: reports.pgr.ousidesla
        type: number
        source: seva 
      - name: owner
        label: reports.pgr.withinsla
        type: number
        source: seva
      - name: collectionamount
        label: reports.pgr.ousidesla
        type: number
        source: seva 
      - name: demandid
        label: reports.pgr.withinsla
        type: number
        source: seva
searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva 
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva 
      - name: complainttype
        label: reports.pgr.complainttype
        type: singlevaluelist
        source: seva
      - name: status
        label: reports.pgr.status
        type: singlevaluelist
        source: seva
        
query: select demand.id, consumercode,consumertype,businessservice,owner,collectionamount,demandid FROM egbs_demand demand INNER JOIN egbs_demanddetail demanddetail ON demand.id=demanddetail.demandid AND demand.tenantid=demanddetail.tenantid WHERE demand.tenantid= $tenantid AND demand.id = $id AND demand.owner = $owner;
