ReportDefinitions:
reportName: GrievanceByType
summary: Report grouped by Grievance Type and status - based on a date period
version: 1.0.0
sourceColumns:
      - name: name 
        label: reports.pgr.complainttype.name
        type: string
        source: egpgr_complainttype 
      - name: status
        label: reports.pgr.seva.status
        type: string
        source: seva 
      - name: withinSLA
        label: reports.pgr.withinsla
        type: number
        source: seva 
      - name: outsideSLA
        label: reports.pgr.ousidesla
        type: number
        source: seva 
      - name: total
        label: reports.pgr.withinsla
        type: number
        source: seva
searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva 
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva 
      - name: complainttype
        label: reports.pgr.complainttype
        type: singlevaluelist
        source: seva
      - name: status
        label: reports.pgr.status
        type: singlevaluelist
        source: seva
        
query: select egct.name as {name}, status as {status}, count(case when (now() - dateclosed) <= 4 THEN 1 ELSE 0)) as {withinSLA},  count(case when (now() - dateclosed) > 4 THEN 1 ELSE 0)) as {outsideSLA}, count(*) as {total} from submission seva join egpgr_complainttype egct on egct.code = seva.serviceCode where seva.createddate >= {fromDate} and seva.createddate <= {toDate} and egct.code = {complainttype} group by {complainttype}, {status}; //alternate query also possible using inner query to save 2 case whens
