swagger: '2.0'
# eGSP YAML Template Version: 1.0 

info:
  version: 1.0.0
  ######################################################
  # All API's are POST. _create,_search,_update for post,get and put. RequestInfo will be part of body. For multiple records we can pass multiple value with comman seperated values*.
  # All _search will be synchronous and all _create and _update will be asynchronous*.
  # RequestInfo and ResponseInfo object should be reffered from Common*.
  # In _search API, tenantId should be passed in query param. In _create/_update, tenantId should be passed in the model.
  # Readonly means that even if these fields are passed in the request, it will be ignored in create/update and will not be added/updated in the entities. The readonly fields might be passed to the _search API's to make use of fields for the search Query API. while calling _search API's even mandatory fields might not be available, it is mandatory only in the _create API's*.
  # All errors will be returned with HTTP error code 400 with customized error code and messages. Consumer of the API need to handle 400 with customized error code and message.
  # Definition must start with Upper case followed by camel case.
  # Every model will have tenantId. Validate tenantId on create.
  # Parameter name must start with small case followed by camel case.
  # Path must be in small case.
  ######################################################
  title: Master and Object Definitions
  description: Definitions of Master and Object used across LandEstate, Acquisition and Advertisement Tax.
  contact:
    name:  eGov
    email: info@egovernments.org
host: phoenix-qa.egovernments.org

schemes:
  - https
basePath: '/lams-maha/v1/definitions'

paths: {}

definitions:

  RegisterName:
    type: object
    description: An object which holds the Register Name Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the RegisterNameMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the RegisterNameMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the RegisterNameMaster
        maxLength: 64
        minLength: 1
      registerName:
        type: string
        description: name of register
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is register is active.
    required:
      - tenantId
      - registerName
      - isActive

  SubRegisterName:
    type: object
    description: An object which holds the Register Name Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the SubRegisterNameMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the SubRegisterNameMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the SubRegisterNameMaster
        maxLength: 64
        minLength: 1
      register:
        $ref: '#/definitions/RegisterName'
      subRegisterName:
        type: string
        description: name of sub register
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is sub register is active.
    required:
      - tenantId
      - subRegisterName
      - register
      - isActive

  Purpose:
    type: object
    description: An object which holds the Register Name Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the PurposeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the PurposeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the PurposeMaster
        maxLength: 64
        minLength: 1
      purpose:
        type: string
        description: name of purpose
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is purpose is active.
    required:
      - tenantId
      - purpose
      - isActive

  ModeOfAcquisition:
    type: object
    description: An object which holds the Mode Of Acquisition Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the ModeOfAcquisitionMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the ModeOfAcquisitionMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the ModeOfAcquisitionMaster
        maxLength: 64
        minLength: 1
      modeOfAcquisition:
        type: string
        description: Mode Of Acquisition Master
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is ModeOfAcquisitionMaster is active.
    required:
      - tenantId
      - modeOfAcquisition
      - isActive

  HoldingType:
    type: object
    description: An object which holds the Holding Type Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the HoldingTypeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the HoldingTypeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the HoldingTypeMaster
        maxLength: 64
        minLength: 1
      holdingType:
        type: string
        description: type of holding
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is HoldingTypeMaster is active.
    required:
      - tenantId
      - holdingType
      - isActive

  CompensationMode:
    type: object
    description: An object which holds the  Compensation Mode Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the CompensationModeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the CompensationModeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the CompensationModeMaster
        maxLength: 64
        minLength: 1
      compensationMode:
        type: string
        description: mode of compensation
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is CompensationModeMaster active.
    required:
      - tenantId
      - compensationMode
      - isActive 

  RoadType:
    type: object
    description: An object which holds the  Road Type Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the RoadTypeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the RoadTypeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the RoadTypeMaster
        maxLength: 64
        minLength: 1
      roadType:
        type: string
        description: name of Mode Of Acquisition Master
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is RoadTypeMaster active.
    required:
      - tenantId
      - roadType
      - isActive
  
  PlaningType:
    type: object
    description: An object which holds the  planning Type Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the PlanningTypeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the PlanningTypeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the PlanningTypeMaster
        maxLength: 64
        minLength: 1
      planningType:
        type: string
        description: name of planning Type
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is PlanningTypeMaster active.
    required:
      - tenantId
      - planningType
      - isActive

  UsageType:
    type: object
    description: An object which holds the  usage Type Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the UsageTypeMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the UsageTypeMaster
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: code of the UsageTypeMaster
        maxLength: 64
        minLength: 1
      usageType:
        type: string
        description: name of usage Type
        maxLength: 128
        minLength: 1
      isActive:
        type: boolean
        description: is usageType active.
    required:
      - tenantId
      - usageType
      - isActive
 
  RenewalScheduler:
    type: object
    description: An object which holds the  Renewal Schedule Type Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the RenewalSchedulerMaster
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the RenewalSchedulerMaster
        maxLength: 128
        minLength: 2
      licenseType:
        type: string
        description: name of license Type
      licenseSubType:
        type: string
        description: name of license sub Type  
      fromDate:
        type: integer
        format: int64
        description: Time in epoch, From date. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      toDate:
        type: integer
        format: int64
        description: Time in epoch, To date. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      licensePeriod:
        type: string
        description: period of license
      startDate:
        type: integer
        format: int64
        description: Time in epoch. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      startMonth:
        type: integer
        format: int64
        description: Time in epoch. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      endDate:
        type: integer
        format: int64
        description: Time in epoch, . Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      endMonth:
        type: integer
        format: int64
        description: Time in epoch,  Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      period:
        type: integer
        format: int64
        description: period
      noOfDaysPerYear:
        type: integer
        format: int64
        description: number of days in a year
    required:
      - tenantId
      - licenseType
      - licenseSubType
      - fromDate
      - toDate
      - licensePeriod
      - startDate
      - startMonth
      - endDate
      - endMonth
      - period
      - noOfDaysPerYear

  BillFrequency:
    type: object
    description: An object which holds the bill frequency Master info
    properties:
      id:
        type: integer
        format: int64
        description: Unique Identifier of the bill frequency master
      tenantId:
        type: string
        readOnly: true
        description: tenant id of the BillFrequencyMaster
        maxLength: 128
        minLength: 2
      frequencyType:
        type: string
        description: name of license Type
        enum:
        - MONTHLY
        - YEARLY
      year:
        type: integer
        format: int64
        description: year of the bill
      fromDate:
        type: integer
        format: int64
        description: Time in epoch, From date. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      toDate:
        type: integer
        format: int64
        description: Time in epoch, To date. Date is inclduing timestamp, dd/MM/yyyy hh24:mi:ss
      licenseNumber:
        type: integer
        format: int64
        description: license number
    required:
      - tenantId
      - frequencyType
      - year
      - fromDate
      - toDate
      - licenseNumber
        
