ReportDefinitions:
#
#Grievance Type Report:
#Grouping the count based on the status with from date and to date:
#select egct.name,count(*),status from submission seva
#join egpgr_complainttype egct on egct.code = seva.serviceCode where seva.createddate >= '2017-06-01' and seva.createddate <= '2017-06-29' group by seva.status,egct.name order by egct.name asc;

#Grouping the count based on the status and grievance type with from date and to date:
#select egct.name,count(*),status from submission seva
#join egpgr_complainttype egct on egct.code = seva.serviceCode where seva.createddate >= '2017-06-01' and seva.createddate <= '2017-06-29' and egct.code = 'BRKNB' group by seva.status,egct.name;

# Both above reports can be achived by creating the report for second case and making status as non mandatory seacrh parameter (Refer revised reportdef yaml)
  - reportName: GrievanceByType
    summary: Report grouped by Grievance Type and status - based on a date period
    version: 1.0.0

    sourceColumns:
      - name: name
        label: reports.pgr.complainttype.name
        type: string
        source: egpgr_complainttype
      - name: registered
        label: reports.pgr.status.registered
        type: number
        source: seva
      - name: inprocess
        label: reports.pgr.status.inprocess
        type: number
        source: completed
      - name: completed
        label: reports.pgr.status.completed
        type: number
        source: reopened
      - name: rejected
        label: reports.pgr.status.reopened
        type: number
        source: seva
      - name: rejected
        label: reports.pgr.status.rejected
        type: number
        source: seva
      - name: withinsla
        label: reports.pgr.status.withinsla
        type: number
        source: seva
      - name: beyondsla
        label: reports.pgr.status.beyondsla
        type: number
        source: seva
      - name: issla
        label: reports.pgr.status.issla
        type: string
        source: seva

    searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva
      - name: complainttype
        label: reports.pgr.complainttype
        type: singlevaluelist
        pattern: http://pgr-master:8080/pgr-master/service/v1/_search?tenantId=default|$..serviceCode|$..serviceName
        source: seva
    query: SELECT ctype.name,count(CASE WHEN cs.status::text = 'REGISTERED'::text THEN 1 ELSE NULL::integer END) AS registered,count(CASE WHEN cs.status::text = ANY (ARRAY['FORWARDED'::character varying::text, 'PROCESSING'::character varying::text, 'NOTCOMPLETED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS inprocess,count(CASE WHEN cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'WITHDRAWN'::character varying::text, 'CLOSED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS completed,count(CASE WHEN cs.status::text = 'REOPENED'::text THEN 1 ELSE NULL::integer END) AS reopened, count(CASE WHEN cs.status::text = 'REJECTED'::text THEN 1 ELSE NULL::integer END) AS rejected, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS withinsla, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS beyondsla, CASE WHEN bool_or((cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text WHEN bool_or((cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text ELSE 'No'::text END AS issla FROM submission cs, egpgr_complainttype ctype WHERE cs.servicecode = ctype.code and ctype.code = $complainttype and cs.createddate >= $fromDate and cs.createddate <= $toDate and cs.tenantid = $tenantid GROUP BY ctype.name;
  
  - reportName: DrillDownByDepartment
    summary: Drill Down Report grouped by Department Name - based on a date period
    version: 1.0.0

    sourceColumns:
      - name: name
        label: reports.pgr.department.name
        type: string
        source: eg_department
      - name: registered
        label: reports.pgr.status.registered
        type: number
        source: seva
      - name: inprocess
        label: reports.pgr.status.inprocess
        type: number
        source: completed
      - name: completed
        label: reports.pgr.status.completed
        type: number
        source: reopened
      - name: rejected
        label: reports.pgr.status.reopened
        type: number
        source: seva
      - name: rejected
        label: reports.pgr.status.rejected
        type: number
        source: seva
      - name: withinsla
        label: reports.pgr.status.withinsla
        type: number
        source: seva
      - name: beyondsla
        label: reports.pgr.status.beyondsla
        type: number
        source: seva
      - name: issla
        label: reports.pgr.status.issla
        type: string
        source: seva

    searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva
    query: SELECT dept.name, count(CASE WHEN cs.status::text = 'REGISTERED'::text THEN 1 ELSE NULL::integer END) AS registered, count(CASE WHEN cs.status::text = ANY (ARRAY['FORWARDED'::character varying::text, 'PROCESSING'::character varying::text, 'NOTCOMPLETED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS inprocess, count(CASE WHEN cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'WITHDRAWN'::character varying::text, 'CLOSED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS completed, count(CASE WHEN cs.status::text = 'REOPENED'::text THEN 1 ELSE NULL::integer END) AS reopened, count(CASE WHEN cs.status::text = 'REJECTED'::text THEN 1 ELSE NULL::integer END) AS rejected, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS withinsla, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS beyondsla, CASE WHEN bool_or((cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text WHEN bool_or((cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text ELSE 'No'::text END AS issla FROM submission cs, eg_department dept, egpgr_complainttype ctype WHERE cs.department=dept.id and cs.servicecode = ctype.code and cs.createddate >= $fromDate and cs.createddate <= $toDate GROUP BY dept.name;
    
  - reportName: DrillDownByBoundary
    summary: Drill Down Report grouped by Boundary Name - based on a date period
    version: 1.0.0

    sourceColumns:
      - name: name
        label: reports.pgr.boundary.name
        type: string
        source: egpgr_complainttype
      - name: registered
        label: reports.pgr.status.registered
        type: number
        source: seva
      - name: inprocess
        label: reports.pgr.status.inprocess
        type: number
        source: completed
      - name: completed
        label: reports.pgr.status.completed
        type: number
        source: reopened
      - name: rejected
        label: reports.pgr.status.reopened
        type: number
        source: seva
      - name: rejected
        label: reports.pgr.status.rejected
        type: number
        source: seva
      - name: withinsla
        label: reports.pgr.status.withinsla
        type: number
        source: seva
      - name: beyondsla
        label: reports.pgr.status.beyondsla
        type: number
        source: seva
      - name: issla
        label: reports.pgr.status.issla
        type: string
        source: seva

    searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva
    query: SELECT boundary.name, count(CASE WHEN cs.status::text = 'REGISTERED'::text THEN 1 ELSE NULL::integer END) AS registered, count(CASE WHEN cs.status::text = ANY (ARRAY['FORWARDED'::character varying::text, 'PROCESSING'::character varying::text, 'NOTCOMPLETED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS inprocess, count(CASE WHEN cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'WITHDRAWN'::character varying::text, 'CLOSED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS completed, count(CASE WHEN cs.status::text = 'REOPENED'::text THEN 1 ELSE NULL::integer END) AS reopened, count(CASE WHEN cs.status::text = 'REJECTED'::text THEN 1 ELSE NULL::integer END) AS rejected, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS withinsla, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS beyondsla, CASE WHEN bool_or((cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text WHEN bool_or((cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text ELSE 'No'::text END AS issla FROM submission cs, eg_boundary boundary, egpgr_complainttype ctype WHERE cs.department=boundary.id and cs.servicecode = ctype.code and cs.createddate >= '2017-06-01' and cs.createddate <= '2017-07-04'GROUP BY boundary.name;
  
  - reportName: Functionary Report
    summary: Functionary Report grouped by Functionary Name - based on a date period
    version: 1.0.0

    sourceColumns:
      - name: name
        label: reports.pgr.functionary.name
        type: string
        source: egpgr_user
      - name: registered
        label: reports.pgr.status.registered
        type: number
        source: seva
      - name: inprocess
        label: reports.pgr.status.inprocess
        type: number
        source: completed
      - name: completed
        label: reports.pgr.status.completed
        type: number
        source: reopened
      - name: rejected
        label: reports.pgr.status.reopened
        type: number
        source: seva
      - name: rejected
        label: reports.pgr.status.rejected
        type: number
        source: seva
      - name: withinsla
        label: reports.pgr.status.withinsla
        type: number
        source: seva
      - name: beyondsla
        label: reports.pgr.status.beyondsla
        type: number
        source: seva
      - name: issla
        label: reports.pgr.status.issla
        type: string
        source: seva

    searchParams:
      - name: fromDate
        label: reports.pgr.datefrom
        type: epoch
        source: seva
      - name: toDate
        label: reports.pgr.dateto
        type: epoch
        source: seva
    query: SELECT us.username AS employeename, count(CASE WHEN cs.name::text = 'REGISTERED'::text THEN 1 ELSE NULL::integer END) AS registered, count(CASE WHEN cs.name::text = ANY (ARRAY['FORWARDED'::character varying::text, 'PROCESSING'::character varying::text, 'NOTCOMPLETED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS inprocess, count(CASE WHEN cs.name::text = ANY (ARRAY['COMPLETED'::character varying::text, 'WITHDRAWN'::character varying::text, 'CLOSED'::character varying::text]) THEN 1 ELSE NULL::integer END) AS completed, count(CASE WHEN cs.name::text = 'REOPENED'::text THEN 1 ELSE NULL::integer END) AS reopened, count(CASE WHEN cs.name::text = 'REJECTED'::text THEN 1 ELSE NULL::integer END) AS rejected, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS withinsla, sum(CASE WHEN (cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 WHEN (cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) > ('01:00:00'::interval * ctype.slahours::double precision) THEN 1 ELSE 0 END) AS beyondsla, CASE WHEN bool_or((cs.status::text = ANY (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (cs.lastmodifieddate - cs.createddate) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text WHEN bool_or((cs.status::text <> ALL (ARRAY['COMPLETED'::character varying::text, 'REJECTED'::character varying::text, 'WITHDRAWN'::character varying::text])) AND (now() - cs.createddate::timestamp with time zone) < ('01:00:00'::interval * ctype.slahours::double precision)) THEN 'Yes'::text ELSE 'No'::text END AS issla FROM submission cs, egpgr_complainttype ctype, egeis_assignment ass, eg_user us WHERE cs.assignee = ass.employeeid and ass.employeeid=us.id and cs.createddate >= $fromDate and cs.createddate <= $toDate GROUP BY us.username;    
   
  - reportName: nextReport
    summary: next report summary
