swagger: '2.0'
info:
  version: 1.0.0
  title: Data Uploader
  description: APIs available for uploading data in bulk and searching upload status.
  contact:
    name: Abhishek Jain
schemes:
  - https
basePath: '/data-uploader/v1/[API endpoint]'
paths:     
  /_create:
    post:
      summary: API to parse excel file and call respective APIs.
      description: >-
        API fetches an xls file based on the id provided to it and parses the excel to create
        requests for respective module APIs.
      parameters:
        - name: UploaderRequest
          in: body
          description: Details of the module and file to be parsed.
          required: true
          schema:
            $ref: '#/definitions/UploaderRequest'
      tags:
        - Data-Upload
      responses:
        '201':
          description: Data uploaded sucessfully.
          schema:
            $ref: '#/definitions/UploaderResponse'
        '400':
          description: Error.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes

            
  /upload-definition/_search:
    post:
      summary: Fetches upload-definitions that are configured.
      description: >-
        Fetched the map of modules and their respective upload-definitions configured
      parameters:
        - name: SearchRequest
          in: body
          description: Details of the module and file to be parsed.
          required: true
          schema:
            $ref: '#/definitions/SearchRequest'
      tags:
        - Data-Upload
      responses:
        '201':
          description: Definitions fetched Successfully sucessfully.
          schema:
            $ref: '#/definitions/ModuleDefResponse'
        '400':
          description: Error.
          schema:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes
definitions:
  
  UploadJob:
    type: object
    description: An upload job 
    properties:
      tenantId:
        description: Unique id for for a tenant.
        type: string
        minLength: 1
        maxLength: 100
      moduleName:
        description: Name of the module for which data upload is intiated.
        type: string
        minLength: 1
        maxLength: 1000
      defName:
        description: Name of the definition for which data upload is intiated.
        type: string
        minLength: 1
        maxLength: 100
      code: 
        type: string
        description: server generated unique id/code for this upload job if the job is accepted
        readOnly: true
      requestFilePath:
        description: file store path of the uploaded request file
        type: string
      responseFilePath:
        description: file store path of the uploaded request file
        type: string
      status:
        description: current status of the job
        type: string
        enum:
          - new
          - InProgress
          - completed
          - failed
      totalRows:
        description: total number of rows in the file to process
        type: integer
      successfulRows:
        description: total number of rows successfully proccessed
        type: integer
      failedRows:
        description: total number of rows failed to be proccessed
        type: integer
      requesterName:
        description: userName of the user requesting this job
        type: string
    required:
      - tenantId
      - moduleName
      - defName
      - requestFilePath


  UploaderResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      UploadJobs:
        type: array
        items: 
          $ref: '#/definitions/UploadJob'
            
  UploaderRequest:
    type: object
    properties:
      UploadJobs:
        type: array
        items: 
          $ref: '#/definitions/UploadJob'
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo
    required:
      - UploadJobs
      - RequestInfo
      
      
      
  SearchRequest:
    type: object
    properties:
      RequestInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo

    required:
      - RequestInfo

      
  ModuleDefResponse:
    type: object
    properties:
      ResponseInfo:
        $ref: >-
          https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo
      ModuleDefs:
        description: Array of modules
        type: array
        items: 
          $ref: '#/definitions/ModuleDefs'
    required:
      - ResponseInfo
      

  Definition:
    type: object
    properties:
      code: 
        description: Def code
        type: string
      name:
        description: Default display name of the deffinition
        type: string
      path:
        description: swagger API path for the API
        type: string
      
  ModuleDefs:
    type: object
    properties:
      code: 
        description: unique key for teh module - ideally x-module from that swagger def
        type: string
      name:
        description: Default display name of the module
        type: string
      Definitions:
        description: Array of definitions for this module
        type: array
        items: 
          $ref: '#/definitions/Definition'
        
