swagger: '2.0'

info:
  version: "1.1.0"
  title: Voucher Service
  description: Voucher services APIs - to create, update and search Voucher. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egf-voucher/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/egf-voucher/contracts/v1-0-0.yml'
x-api-id: 'org.egov.egf.voucher'
paths:
    /vouchers/_search:
      post:
        summary: Get the list of vouchers
        description: vouchers
        tags: 
          - Voucher
        parameters:
          - name: requestInfo
            in: body
            description: Common Request info for the Services
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
          - name: tenantId
            in: query
            description: Unique id for  a tenant.
            required: true
            type: string
            format: varchar
          - name: ids
            type: array
            items: 
              type: integer
            format: int64
            in: query
            maxItems: 50
            description: comma seperated list of Ids 
          - name: name
            type: string
            in: query
            description: Voucher Name
            maxLength: 16
          - name: type
            type: string
            in: query
            description: Voucher Type
            maxLength: 16
          - name: description
            type: string
            in: query
            description: description of the Voucher
            maxLength: 256
          - name: voucherNumber
            type: string
            in: query
            description: voucher number of the Voucher
            maxLength: 32
          - name: voucherDate
            type: string
            format: date
            in: query
            description: voucher date of the Voucher
          - name: fund
            type: integer
            format: int64
            in: query
            description: fund of the Voucher
          - name: fiscalPeriod
            type: integer
            format: int64
            in: query
            description: fiscal period of the Voucher
          - name: status
            type: integer
            format: int64
            in: query
            description: status of the Voucher
          - name: originalVhId
            type: integer
            format: int64
            in: query
            description: original vh id of the Voucher
          - name: refVhId
            type: integer
            format: int64
            in: query
            description: reference vh id of the Voucher
          - name: moduleId
            type: integer
            format: int64
            in: query
            description: module id of the Voucher
          - name: glcode
            type: string
            in: query
            description: glcode of the voucher
          - name: pageSize
            type: integer
            format: int32
            in: query
            description: Number of records in a per page in  the Search Results, Default value is 20
          - name: offSet
            type: integer
            format: int32
            in: query
            description: page number of the Search Results, Default value is 0
        responses:
          200:
            description: Voucher retrieved Successfully
            schema:
              $ref: '#/definitions/VoucherResponse'
          400:
            description: Invalid Input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
    /vouchers/_create:
      post:
        summary: Create  new  vouchers
        description: Create  new vouchers. Mandatory fields are considered from application configuration "Default transactoin Attributes" . Fields marked mandatory are validated at the time of voucher createion . 
        tags: 
          - Voucher
        parameters:
          - name: tenantId
            in: query
            description: Unique id for  a tenant.
            required: true
            type: string
            format: varchar
          - name: voucherRequest
            in: body
            description: Create  new 
            schema:
              $ref: '#/definitions/VoucherRequest'
        responses:
          201:
            description: Voucher created Successfully
            schema:
              $ref: '#/definitions/VoucherResponse'
          400:
            description: Invalid Input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
    /vouchers/_update:
      post:
        summary: Update any of the vouchers
        description: Update any of the vouchers
        tags: 
          - Voucher
        parameters:
          - name: tenantId
            in: query
            description: Unique id for  a tenant.
            required: true
            type: string
            format: varchar
          - name: voucherRequest
            in: body
            description: common Request info
            schema:
              $ref: '#/definitions/VoucherRequest'
        responses:
          200:
            description: Voucher updated Successfully
            schema:
              $ref: '#/definitions/VoucherResponse'
          400:
            description: Invalid Input
            schema:
              $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
definitions:
    Voucher:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier of the Voucher
        type:
          type: string
          description: Voucher Type
          enum:
            - Journal Voucher
            - Payment
            - Receipt
        name:
          $ref: "#/definitions/VoucherName"
    
        description:
          type: string
          description: A detailed description of the voucher being created.
          maxLength: 256
        voucherNumber:
          type: string
          description:  | 
                        Voucher Number. It considers the appllication configuration attribute "Automatic Voucher Number Generation"
                        If this configuration is set to true this data is generated by server . Otherwise this is Mandatory for the caller to provide this           
          maxLength: 32
        voucherDate:
          type: string
          format: date
          description: Date on which voucher is created. Post dates are not allowed. If the financial year is closed then those dates are not allowed to create.
        fund:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Fund"
        fiscalPeriod:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/FiscalPeriod"
        status:
          $ref: "#/definitions/EgfStatus"
        originalVhId:
          type: integer
          format: int64
          description: id of the main voucher when voucher is reversed.
        refVhId:
          type: integer
          format: int64
          description: id of the reversal voucher when voucher is reversed .
        moduleId:
          type: integer
          format: int64
          description: id of the external module which is calling voucher creation.
        ledgers:
          type:  array
          description:  ledgers of the Voucher
          items:
            $ref: "#/definitions/Ledger"
        vouchermis:
          $ref: "#/definitions/Vouchermis"
      required:
      - name
      - type
      - voucherDate
    Ledger:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier 
        orderId:
          type: integer
          format: int32
          description: order id 
        chartOfAccount:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/ChartOfAccount"
        glcode:
          type: string
          description: glcode 
          maxLength: 16
        debitAmount:
          type: number
          format: double
          description: debit amount 
        creditAmount:
          type: number
          format: double
          description: credit amount 
        function:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Function"
          description: |
                       This considers application configuration property "Allow Multiple Functions". If this value set to true then 
                       System will expect function in ledger entry else system will expect function in vouchermis 
          
        ledgerDetails:
          type:  array
          description:  ledgers 
          items:
            $ref: "#/definitions/LedgerDetail"
      required:
      - glcode
      - debitAmount
      - creditAmount
    Vouchermis:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier 
        fundsource:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Fundsource"
        billNumber:
          type: string
          description: bill number 
        boundary:
          type: integer
          format: int64
          description: boundary 
        departmentId:
          type: integer
          format: int64
          description: department id 
        scheme:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Scheme"
        subScheme:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/SubScheme"
        functionary:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Functionary"
        function:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Function"
        sourcePath:
          type: string
          description: source path 
        budgetAppropriationNo:
          type: string
          description: budget appropriation no 
        budgetCheckRequired:
          type: boolean
          description: budget check required 
    LedgerDetail:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier
        accountDetailType:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/AccountDetailType"
        accountDetailKey:
          $ref: "https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/AccountDetailKey"
        amount:
          type: number
          format: double
          description: Subledger amount
      required:
      - accountDetailType
      - accountDetailKey
      - amount
    VoucherRequest:
      description: Contract class to receive request. Array of Voucher items  are used in case of create . Where as single Voucher item is used for update
      properties:
        requestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/RequestInfo'
        vouchers:
          description: Used for search result and create only
          type:  array
          items:
            $ref: '#/definitions/Voucher'
        voucher:
          $ref: '#/definitions/Voucher'
    VoucherResponse:
      description: Contract class to send response. Array of Voucher items  are used in case of search results or response for create. Where as single Voucher item is used for update
      properties:
        responseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
        vouchers:
          description: Used for search result and create only
          type:  array
          items:
            $ref: '#/definitions/Voucher'
        voucher:
          $ref: '#/definitions/Voucher'
        page:
          $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/contracts/v1-0-0.yml#/definitions/Page'
    EgfStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier of the EgfStatus
        moduleType:
          type: string
          description: module type of the EgfStatus
        code:
          type: string
          description: code of the EgfStatus
        description:
          type: string
          description: description of the EgfStatus
      required:
      - id
      - moduleType
      - code
      - description    
    VoucherName:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique Identifier of the EgfStatus
        name:
          type: string
          description: name of the voucher
        validUpto :
          type: string
          format: date
          description:  This date will be used in the system to validate till when this kind of vouchers needs to be allowed from the Journal Voucher screen. This date can be left blank(non-mandatory)
        exclude:
          type: boolean
          description: Values can be Y or N. If value is Y , then this item will be listed in the Journal voucher screen. If the value is N, then this item will not list in the Journal voucher option.
      required:
      - name
      - exclude
        


