ServiceMaps:
 serviceName: PrpertyTax
 mappings:
  - version: 1.0.0
    indexName: pt_index
    indexType: pt_type
    fromTopic: egov.es
    indexID: $.User.mobileNumber
    jsonPath:
    indexMap:
     - inJsonPath: $.properties[index].name
       outJsonPath: $.propertyname
       indexDatatype: text
     - inJsonPath: $.properties[index].code
       outJsonPath: $.propertycode
       indexDatatype: text
    omitPaths:
      - $.properties[index].user.mother
      - $.properties[index].user.phone
    maskPaths:
      - $.properties[index].user.phone
      - $.properties[index].user.email
    hashPaths:
      - $.properties[index].user.userid
      - $.properties[index].user.name