ServiceMaps:
 serviceName: DummyService
 version: 1.0.0
 mappings:
  - topic: save-service-db
    indexes:
    - name: cs_index
      type: cs_type
      id: $.serviceReq.serviceRequestId
      isBulk: false
      jsonPath: 
    - name: dm_index
    	 type: dm_type
    	 id: $.serviceReq.serviceRequestId
    	 isBulk: false
    	 jsonPath: 

  - topic: update-service-db
    indexes:
	  - name: pt_index
    	type: pt_type
    	id: $.serviceReq.serviceRequestId
    	isBulk: false
    	jsonPath:
